### ISSUE TITLE
StackLayout ignores disabling of size hints

### ISSUE THREAD

**Issue by jtrunick** [kivy/kivy#1076]
StackLayout should allow specifying either the x/y size or both after disabling the x/y hint with None.

Likely issue area:
https://github.com/kivy/kivy/blob/master/kivy/uix/stacklayout.py#L202-214

Example code (buttons should appear relatively square):

```
    StackLayout:
        size: 50, 200
        orientation: 'bt-lr'

        Button:
            size_hint: 1, None
            height: self.width
            text: 'hi'

        Button:
            size_hint: 1, None
            height: self.width
            text: 'world'
```
