### ISSUE TITLE
Label refs no longer work after commit: 3082cc7 introduce lazy texture

### ISSUE THREAD

**Issue by joseph-jnl** [kivy/kivy#1102]
Label refs work when checked out to commit cdbb394 or before, stops working after commit: 3082cc7 'introduce lazy texture'. Tried looking at the diff but I couldn't figure out what was causing the issue.

MarkupRefTest.py

```
import kivy
from kivy.app import App
from kivy.uix.widget import Widget

class MarkupRefTest(App):
    def build(self):
        reftest = RefTest()
        return reftest

class RefTest(Widget):
    pass

MarkupRefTest().run()
```

MarkupRefTest.kv

```
#:kivy 1.6.0    
<RefTest>
    BoxLayout:
        orientation: 'vertical'
        size: root.size
        Label:
            text: '[ref=ref1][size=38sp][b]Press[/b] Me[/size][/ref]'
            markup: True
            on_ref_press: print('ref1')
        Button:
            on_press: print(lbl1.refs)
            on_press: print(lbl2.refs)
        Label:
            id: lbl2
            text: '[ref=ref2]Press Me[/ref]'
            markup: True
            on_ref_press: print('ref2')
```
