### ISSUE TITLE
no way to use Dynamic Classes with ListAdapter

### ISSUE THREAD

**Issue by dusty-phillips** [kivy/kivy#1347]
Given the very simple `main.py`:

``` python
from kivy.app import App


class DynamicClassTest(App):
    pass

DynamicClassTest().run()
```

It is possible to construct `ListAdapter`s using normal classes or templates. Both these KV Language files work just fine:

``` yaml
#:import la kivy.adapters.listadapter
#:import lb kivy.uix.label

ListView:
    adapter:
        la.ListAdapter(
        data=[str(i) for i in range(10)],
        cls=lb.Label)(venv)(master)
```

and

``` yaml
#:import la kivy.adapters.listadapter

[Dynlabel@Label]:
    text: ctx.text

ListView:
    adapter:
        la.ListAdapter(
        data=[str(i) for i in range(10)],
        template="Dynlabel")
```

The latter syntax is deprecated in favor of dynamic classes, but I cannot find any way to make dynamic classes work with kivy syntax:

``` yaml
#:import la kivy.adapters.listadapter

<Dynlabel@Label>:
    text: ctx.text

ListView:
    adapter:
        la.ListAdapter(
        data=[str(i) for i in range(10)],
        cls=Dynlabel)
```

fails with a `name 'Dynlabel' is not defined` error, while

``` yaml
#:import la kivy.adapters.listadapter

<Dynlabel@Label>:
    text: ctx.text

ListView:
    adapter:
        la.ListAdapter(
        data=[str(i) for i in range(10)],
        cls="Dynlabel")
```

yields a `TypeError: 'str' object is not callable`.

While it would be handy if one of these syntaxes could be supported, it may also be wise to consider changing the API so that it's possible to instantiate a ListAdapter using "kivy magic". The KV Language could then look something like:

``` yaml
ListView:
    adapter:
        ListAdapter:
            data: []
            cls: Dynlabel
```

In any event, the documentation for ListAdapter is out of date because it references KV Lange templates, which are deprecated, and does not support dynamic classes in any way.
