### ISSUE TITLE
.kv File not being read properly on the Raspberry Pi

### ISSUE THREAD

**Issue by zanechua** [kivy/kivy#1394]
Using the Raspberry Pi and the pong game example, i am unable to change the background of the pong game in the kv file.

Example Section of the kv file:

```
<PongGame>:
    ball: pong_ball
    player1: player_left
    player2: player_right

    canvas:
        Rectangle:
            source: 'background.jpg'
            pos: self.center_x-5, 0
            size: 10, self.height
```

That gives a invalid data after declaration error. However, if i don't change the kv file and change the python file instead by adding this section below:

```
class PongGame(Widget):
    ball = ObjectProperty(None)
    player1 = ObjectProperty(None)
    player2 = ObjectProperty(None)

    def __init__(self, **kwargs):
        super(PongGame, self).__init__(**kwargs)
        #texture = CoreImage('background.jpg').texture
        with self.canvas.before:
            self.rect = Rectangle(pos=self.pos, size=self.size, source='background.jpg')
```

Then it works. Kovak on IRC helped me and suggested i should post this so i did. I believe the kv file is not getting parsed properly on the Raspberry Pi as i have another project that's not working properly on the Pi.
