### ISSUE TITLE
kivy.lang: could be an issue?

### ISSUE THREAD

**Issue by Coffelius** [kivy/kivy#189]
This works:

```
#:import thecursor cursor
Widget:
    thecursor.Cursor:
    FloatLayout:
        size: self.parent.size
        Button:
            text: "text"
            size_hint:(0.1, 0.1)
            pos_hint:{'x':0.45, 'y':0.45}
```

---

This don't work, raising kivy.factory.FactoryException: Unknown class <thecursor.Cursor>

```
#:import thecursor cursor
Widget:
    FloatLayout:
        size: self.parent.size
        Button:
            text: "text"
            size_hint:(0.1, 0.1)
            pos_hint:{'x':0.45, 'y':0.45}
    thecursor.Cursor:
```

The difference is the order of the children of Widget
