### ISSUE TITLE
drag order miss-lead in pagelayout widget

### ISSUE THREAD

**Issue by gordianknotC** [kivy/kivy#1914]
consider the following kv lang

```
PageLayout:
    Button:
        text: 'page1'
    Button:
        text: 'page2'
    Button:
        text: 'page3'
```

PageLayout functioned ok in above code, but what if we append widgets more than three?

```
PageLayout:
    Button:
        text: 'page1'
    Button:
        text: 'page2'
    Button:
        text: 'page3'
    Button:
        text: 'page4'
```

When flipping page1 to page2, it was page3 instead of page2 was dragged.

_
_
