### ISSUE TITLE
blank space in boxlayout

### ISSUE THREAD

**Issue by wrabbit-revisited** [kivy/kivy#1955]
I am trying to create a layout where the middle section has an absolute height. So far no luck. The boxlayout containing the button leaves empty space above the button.

btw it would be Nice if you could attach arbitrary files to these issues.
## kv

```
# File name: main.kv
#:kivy 1.7.0

<MyButton@Button>:
    color: .8,.9,0,1
    font_size: 32

<TopWidget>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: 'vertical'
        MyButton:
            text: "TopBtn"
<MiddleWidget>:
    BoxLayout:
        size: root.width, _my_button.height
        pos: root.pos
        orientation: 'vertical'
        MyButton:
            id: _my_button
            height: 50
            text: "MiddleBtn"
<BottomWidget>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: 'vertical'
        MyButton:
            text: "BottomBtn"
<Main@Screen>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: 'vertical'
        TopWidget:
            id: _top_widget
        MiddleWidget:
            id: _middle_widget
            size_hint_y: None
        BottomWidget:
            id: _bottom_widget
```

![screen shot 2014-03-11 at 7 26 48 am](https://f.cloud.github.com/assets/450690/2398499/063062dc-a9f6-11e3-86f4-3a819ffbdf68.png)
## python

```
# File name: main.py
import kivy
kivy.require('1.7.0')

from kivy.app import App
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager
from kivy.uix.widget import Widget

Builder.load_file('main.kv')

class TopWidget(Widget):
    pass

class MiddleWidget(Widget):
    pass

class BottomWidget(Widget):
    pass

class MainScreenManager(ScreenManager):
    pass

class MainScreenManagerApp(App):
    def build(self):
        return MainScreenManager()

if __name__=="__main__":
    MainScreenManagerApp().run()
```
