### ISSUE TITLE
splitter exceeds boundaries

### ISSUE THREAD

**Issue by batwicket** [kivy/kivy#1982]
The example below creates two vertical splitters. The lower one can be resized such that the splitter bar goes through the higher one.

```
# File name: main.kv
#:kivy 1.7.0

BoxLayout:
    orientation: 'vertical'
    Button:
        text: "Btn0"
    Splitter:
        sizable_from: 'top'
        BoxLayout:
            orientation: 'horizontal'
            BoxLayout:
                orientation: 'vertical'
                Button:
                    text: "Btn1"
                Splitter:
                    sizable_from: 'top'
                    Button:
                        text: "Btn2"
            Splitter:
                sizable_from: 'left'
                Button:
                    text: "Btn3"
```

```
# File name: main.py
import kivy
kivy.require('1.7.0')
from kivy.app import App

class MainApp(App):
    pass

if __name__=="__main__":
    MainApp().run()
```

![screen shot 2014-03-18 at 4 13 42 pm](https://f.cloud.github.com/assets/6760834/2454821/04da358c-aef3-11e3-82b1-b7a6361a6150.png)
![screen shot 2014-03-18 at 4 13 55 pm](https://f.cloud.github.com/assets/6760834/2454823/083c0322-aef3-11e3-94dd-e3b9f76f3941.png)
