### ISSUE TITLE
Incorrect position of Label with texture_size and top/right/center

### ISSUE THREAD

**Issue by tshirtman** [kivy/kivy#2029]
When binding label size to texture_size, and using alias properties to position it relatively to its size, it seems the update of texture_size doesn't update the position, the following examples show the issue.

```
from kivy.base import runTouchApp
from kivy.lang import Builder

KV = '''
FloatLayout:
    Label:
        id: a
        text: 'a'
        center: root.center
        font_size: 300
        size_hint: None, None
        size: self.texture_size
    Label:
        top: a.top
        text: 'b'
        x: a.right
        font_size: 300
        size_hint: None, None
        size: self.texture_size
    Label:
        top: a.top
        right: a.x
        text: 'c'
        font_size: 300
        size_hint: None, None
        size: self.texture_size
'''

if __name__ == '__main__':
    runTouchApp(Builder.load_string(KV))
```

```
from kivy.base import runTouchApp
from kivy.lang import Builder

KV = '''

FloatLayout:
    on_touch_down: print(a.center, (a.x + a.width/2, a.y + a.height/2),\
    self.center, (self.x + self.width/2, self.y + self.height/2))
    Label:
        font_size: 300
        size_hint: None, None
        size: self.texture_size
        id: a
        text: 'a'
        center: root.center
'''

if __name__ == '__main__':
    runTouchApp(Builder.load_string(KV))
```

The fact that size is bound to texture_size and that position depends on size (whether it's from top/right or center) seems to be the cause of the issue, however, these aliasproperties are observing size as well as pos, so the cascading of dispatch should theorically happen.
