### ISSUE TITLE
Pyinstaller Linux App - (pygame parachute)

### ISSUE THREAD

**Issue by b3ni** [kivy/kivy#2034]
I have the following error when running a compiled application with PyInstaller for linux.
Compile the executable in Ubuntu 12.04 and run the application on Ubuntu 13.10.

```
Fatal Python error: (pygame parachute) Segmentation Fault
Abortado (`core' generado)
```

In Ubuntu 12.04 runs ok.

Application

```
# this is for testing angle_stop/angle_start
from kivy.base import EventLoop
EventLoop.ensure_window()

from kivy.app import App
from kivy.lang import Builder

kv = '''
BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        size_hint_y: None
        height: sp(100)
        BoxLayout:
            orientation: 'vertical'
            Slider:
                id: e1
                min: -360.
                max: 360.
            Label:
                text: 'angle_start = {}'.format(e1.value)
        BoxLayout:
            orientation: 'vertical'
            Slider:
                id: e2
                min: -360.
                max: 360.
                value: 360
            Label:
                text: 'angle_end = {}'.format(e2.value)

    BoxLayout:
        size_hint_y: None
        height: sp(100)
        BoxLayout:
            orientation: 'vertical'
            Slider:
                id: wm
                min: 0
                max: 2
                value: 1
            Label:
                text: 'Width mult. = {}'.format(wm.value)
        BoxLayout:
            orientation: 'vertical'
            Slider:
                id: hm
                min: 0
                max: 2
                value: 1
            Label:
                text: 'Height mult. = {}'.format(hm.value)
        Button:
            text: 'Reset ratios'
            on_press: wm.value = 1; hm.value = 1

    FloatLayout:

        canvas:
            Color:
                rgb: 1, 1, 1
            Ellipse:
                pos: 100, 100
                size: 200 * wm.value, 201 * hm.value
                source: 'data/logo/kivy-icon-512.png'
                angle_start: e1.value
                angle_end: e2.value

'''

class CircleApp(App):
    def build(self):
        return Builder.load_string(kv)

CircleApp().run()
```

The execution log: https://gist.github.com/b3ni/9910608
The spec pyinstaller file: https://gist.github.com/b3ni/9910729
