### ISSUE TITLE
Line's dash_offset/dash_length only work with width: 1

### ISSUE THREAD

**Issue by tshirtman** [kivy/kivy#2037]
```
Line:
    points: 100, 100, 200, 200
    dash_offset: 10
    dash_lenght: 10
    width: 2
```

doesn't display the line dashed, while

```
Line:
    points: 100, 100, 200, 200
    dash_offset: 10
    dash_lenght: 10
    width: 1
```

does.

Probably broken since Line's width option have been fixed.
