### ISSUE TITLE
updating text of Label don't work correctly

### ISSUE THREAD

**Issue by tshirtman** [kivy/kivy#205]
seems related to the use of text_size, when the new string is shorter than the new one, the label display the end of the old value, instead of the new one…

in the following example, clicking on the button should change the text to "hop" but it get changed to "mlkfj slmkjdflmk some very long string'''
# 

```
#!/usr/bin/env python
from kivy.app import App
from kivy.uix.label import Label
from kivy.uix.widget import Widget
from kivy.uix.scatter import Scatter
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.button import Button
from kivy.properties import StringProperty

class MyWidget(FloatLayout):
    string = StringProperty('''dlfmksjdml kfjsmldj fmlsdjkfml sjdklmf
    jlmskdjflmk jsmldkfjm lskjdlmfkj slmkdjfml kjsmldkjf lmksjdlmkfj
    mlksjdlmkfj lmksjdmlfjs ldkfjmslkd jfmlkjs mdlkjfm lsjkdmlfkj mslkjdflm
    kjsmldjkfm lsjkdmlkfj slmkjdflmk some very long string''')

    def update_str(self):
        print self.string
        self.string = 'hop'


class TestCase(App):
    def build(self):
        return MyWidget()

if __name__ == '__main__':
    TestCase().run()
```
# 

```
#:kivy 1.0.7

<MyWidget>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: root.string
            text_size: root.width, None

        Button:
            text: 'change'
            on_release: root.update_str()
```
