### ISSUE TITLE
expression not updated unless a Label is in Rule?

### ISSUE THREAD

**Issue by tshirtman** [kivy/kivy#2105]
Something fishy going on here, if i uncomment the Label line here, colors are correctly displayed

```
from kivy.base import runTouchApp
from kivy.lang import Builder

KV = '''
FloatLayout:
    Bin:
        bin_type: 'A'
        pos_hint: {'center_y': .33, 'center_x': .2}
        size_hint: None, None
    Bin:
        bin_type: 'B'
        pos_hint: {'center_y': .5, 'center_x': .2}
        size_hint: None, None
    Bin:
        bin_type: 'C'
        pos_hint: {'center_y': .66, 'center_x': .2}
        size_hint: None, None

<Bin@Widget>:
    bin_type: 'A'

    canvas:
        Color:
            rgba: {'A': (0, .2, .5, 1), 'B': (.4, 0, .5, 1), 'C': (.8, 1, .8)}[self.bin_type or 'A']

        Ellipse:
            pos: self.pos
            size: self.size
    Label: #weird workaround, XXX investigate
'''

runTouchApp(Builder.load_string(KV))
```

(also on gist https://gist.github.com/tshirtman/11208983)

I guess there is a failure in the evaluation of the expression (no binding), and the Label is somehow accidentally fixing that, even if it doesn't bind to anything.
