### ISSUE TITLE
Color problem kv file

### ISSUE THREAD

**Issue by roberto-buratti** [kivy/kivy#2118]
Hi, I'm a a kivy-beginner so first of all I apologize if this issue is not a bug.
I tried to to customize the PongApp program found in the tutorial.
Specifically I tried to add different colors to the two score labels with the following:

```
Label:
    font_size: 70  
    center_x: root.width / 4
    top: root.top - 50
    text: str(root.player1.score)
    color: [1, 0, 0, 1]

Label:
    font_size: 70  
    center_x: root.width * 3 / 4
    top: root.top - 50
    text: str(root.player2.score)
    color: [1, 1, 0, 1]
```

But this caused the two PongPaddle's and the PongBall to became yellow too, like the second Label.
Note that removing the color attribute from the second label did not colour the ball and the paddles.
Why? did I do some mistake or is it really a bug?
Many thank in advance.
Rob
