### ISSUE TITLE
RstDocument document_root not honoured for images

### ISSUE THREAD

**Issue by mjmare** [kivy/kivy#2179]
With this KV:

```
    RstDocument:
        id: _rst
        document_root: 'rst'
        source: 'test1.rst'
```

And this rst file:

```
Some text

.. image:: baha.jpg
```

The 'test1.rst' file and the image 'baha1.jpg' are in the same directory 'rst' (relative to the app root).
The test1.rst is found and rendered correctly. However this does not hold for the baha1.jpg image referenced in the rst file (it is still searched for in the app root). 
I think the lookup for images should also be relative to the document_root.  
##
