### ISSUE TITLE
Two widgets show different values for the same variable

### ISSUE THREAD

**Issue by ceremcem** [kivy/kivy#2218]
As you can see in the screenshots, there are two widgets in a custom widget. %99 of the time in the tests, the switch and the label shows correct values.  But if I click very fast on the switch, it sometimes fails to represent correct value of its own variable but label always represents the correct value of the switch's variable. 

![kivy-1](https://cloud.githubusercontent.com/assets/6639874/3113363/e55e8bca-e6d5-11e3-80e4-ef0b7362df26.png)

![kivy-2](https://cloud.githubusercontent.com/assets/6639874/3113325/0adc7b38-e6d5-11e3-80db-a8711cac4e0c.png)

```
<CcaSwitch@BoxLayout>
    switch: sid.__self__
    Switch:
        id: sid
        on_active: root.send_bit("from-gui", *args)
    BoxLayout:
        orientation: 'horizontal'
        Label:
            text: "iletimde" if sid.active else "kesimde"
        Label:
            text: root.real_value
        Label:
            text: root.refresh_message
```

```
class CcaSwitch(BoxLayout):
    #counter = Counter()

    name = StringProperty()
    addr = StringProperty()
    real_value = StringProperty()
    refresh_message = StringProperty()

    def __init__(self, *args, **kwargs):
        BoxLayout.__init__(self, *args, **kwargs)
        Clock.schedule_once(self.on_load)

    def on_load(self, *l):
        self.io = cca_dio(self.addr)
        self.io.add_update_callback(self.on_rx)
        tmp = self.io.val

    def refresh(self, dt):
        pass

    def on_rx(self, value):
        self.switch.active = bool(value)

        #self.real_value = ???
        #self.refresh_message = ???

    def send_bit(self, *args):

        print("ACTIVE STATE CHANGED!!!")
        if args[0] == "from-gui":
            state = str(int(args[2]))
            self.io.val = int(state)
        else:
            print("NON GUI CALL")
```

How should I trace this problem? 
##
