### ISSUE TITLE
Overriding insert_text in TextInput works strange on Android

### ISSUE THREAD

**Issue by NumesSanguis** [kivy/kivy#2350]
This code works on Ubuntu but gives 'undefined' symbols on Android when typing anything:
# main.py

```
class AnswerTextInput(TextInput):
     def insert_text(self, substring, from_undo=False):
         substring = substring.lower()
         return super(AnswerTextInput, self).insert_text(substring, from_undo=from_undo)
```
# kivy file

```
AnswerTextInput:
    id: txt_field
    txt: ""
    font_size: '20sp'
    multiline: False
    size_hint_x: .8
```

I also tried removing the first characters from the string in the input field, but this did nothing (which worked on Ubuntu). However I'm not sure if this is the same problem.
