### ISSUE TITLE
String transform methods (upper/lower/etc) do not bind properties in kivy lang

### ISSUE THREAD

**Issue by geeklint** [kivy/kivy#2434]
Possibly part of a larger issue, but a common functionality I would expect would be to be able to call methods on strings to transform their case. When this is used in the kivy lang file the properties do not bind & update as one would expect.

Does not work:

```
BoxLayout:
    Label:
        text: ti.text.upper()
    TextInput:
        id: ti
```

Workaround / expected functionality:

```
BoxLayout:
    Label:
        text: str.upper(ti.text)
    TextInput:
        id: ti
```
##
