### ISSUE TITLE
RelativeLayout bug whenever any widget is placed before it in the widget Tree

### ISSUE THREAD

**Issue by LudwigWild** [kivy/kivy#2435]
Here's a simple way to reproduce this bug :
## .py file

``` javascript
import kivy
kivy.require('1.8.0')

from kivy.app import App
from kivy.uix.boxlayout import BoxLayout

class RootWidget(BoxLayout):
    pass

class KivyApp(App):
    def build(self):
        return RootWidget()

if __name__ == '__main__':
    KivyApp().run()
```
# .kv file

```
#:kivy 1.8.0

<RootWidget>:
    FloatLayout:
        canvas:
            Color:
                rgba: [0.4, 0.7, 0.2, 1]
            Rectangle:
                pos: self.pos
                size: self.size

    RelativeLayout:
        canvas:
            Color:
                rgba: [0.7, 0.7, 0.7, 1]
            Rectangle:
                pos: self.pos
                size: self.size
    Widget:
        canvas:
            Color:
                rgba: [0.1, 0.4, 0.7, 1]
            Rectangle:
                pos: self.pos
                size: self.size
```

We should see 3 rectangles of the same size with different colors, but we can't see the color of the second one (the canvas of the RelativeLayout). Instead we get a no-color (black) one.
#### Examples

RelativeLayout is 1st is the twidget tree : http://screencloud.net/v/7Wj1
RelativeLayout is 2nd is the twidget tree : http://screencloud.net/v/CRFy (bug)
#### Here are the arrangements that correctly show the 3 colored bands :

**RelativeLayout**
_FloatLayout
Widget_

**RelativeLayout**
_Widget
Floatlayout_
#### Here are the arrangements that **don't** correctly show the 3 colored bands :

_Widget_
**RelativeLayout**
_FloatLayout_

_FloatLayout_
**RelativeLayout**
_Widget_

_Widget
FloatLayout_
**RelativeLayout**

_FloatLayout
Widget_
**RelativeLayout**

In my example, my root widget is a BoxLayout, but the bug persists even with a GridLayout based root widget. It might even persist with all the others widgets as a root widget (I didn't test the others).
