### ISSUE TITLE
ScrollView delays switching the background_down of buttons

### ISSUE THREAD

**Issue by MohsenHassani** [kivy/kivy#2443]
Hello guys,
When I use ScrollView to cover some buttons, the background_down switching of  buttons will fail to work, I need to hold the buttons for about 2 seconds (1500ms) so that I can see the background_down image.

class HomeScreen(Screen):
    pass

<HomeScreen>:
    name: 'home_screen'

```
ScrollView:
    do_scroll_x: False

    GridLayout:
        cols: 1
        spacing: '10dp'
        padding: '5dp'
        size_hint_y: None
        height: self.minimum_height

        HomeScreenButtons:
            text: 'Grammar'

        HomeScreenButtons:
            text: 'Vocabulary'

        HomeScreenButtons:
            text: 'Listening'

        HomeScreenButtons:
            text: 'Reading'
```
