### ISSUE TITLE
embedded custom classes don't have ids

### ISSUE THREAD

**Issue by cltrudeau** [kivy/kivy#2479]
If you define your own class extending from a widget and use it in the kv-lang inside another class it does not get an id.  There isn't anything in the documentation that says you can do this, but it seems like it fits with how the kv-lang is constructed.

```
<InsideBox>:
    size_hint: (1, 1)
    Label:                    
        id: in_left            
        text: "Inside Left"              
    Label:                                    
        id: in_right              
        text: "Inside Right"              

<OutsideBox>:                              
    size_hint: (1, 1)                    
    orientation: 'vertical'              
    Label:                                
        id: out_over            
        text: "Over"                      
    InsideBox:                    
        id: out_insidebox  
    Label:                                                                      
        id: out_under
        text: "Under"
```

```
class InsideBox(BoxLayout):
    def __init__(self, *args, **kwargs):
        super(InsideBox, self).__init__(*args, **kwargs)                        
        print 'inside ids:',  self.ids                                          

class OutsideBox(BoxLayout):                                                    
    def __init__(self, *args, **kwargs):                                        
        super(OutsideBox, self).__init__(*args, **kwargs)                      
        print 'outside ids:',  self.ids                                        

class MyApp(App):                                                              
    def build(self):                                                            
        #return InsideBox()                                                    
        return OutsideBox()
```

In the code above, "inside ids" will be empty even though it should have two Labels.  The "outside ids" shows correctly.  If you change the comment in MyApp and just have the InsideBox returned, it works as expected.
