### ISSUE TITLE
problems with horizontal scroll (OS X?)

### ISSUE THREAD

**Issue by cltrudeau** [kivy/kivy#2486]
I can't seem to get horizontal scrolling to work.  Vertical is fine and if I force the bars to show or resize the window I can see that the child pane is bigger, but it won't scroll left and right.  I'm having the problem on OS X, I'm not sure if this is an OS specific thing or not.  This appears to be similar to the closed ticket #840, but that was from two years ago.

```
<RootBox>:                                                                    
    size_hint: (1, 1)

    ScrollView:                        
        id: scroller                                  
        size_hint: (1, 1)
        do_scroll_x: True                                                      
        do_scroll_y: True          
        scroll_type: ['bars', 'content']
```

```
class RootBox(BoxLayout):                                                      
    def __init__(self, *args, **kwargs):                                        
        super(RootBox, self).__init__(*args, **kwargs)                          

        self.layout = GridLayout(rows=10, cols=50, padding=(10, 15), spacing=8,
            size_hint=(None, None))                                            

        self.layout.bind(minimum_height=self.layout.setter('height'))          
        self.layout.bind(minimum_width=self.layout.setter('width'))            
        self.ids.scroller.add_widget(self.layout)                              

        for j in range(10):                                                    
            for k in range(50):                                                
                label = Label(text='asdf %d.%d' % (j, k), width=150,            
                    size_hint=(None, None))                                    
                self.layout.add_widget(label)                                  

        self.ids.scroller.scroll_x = 0                                          
        self.ids.scroller.scroll_y = 0 
```
##
