### ISSUE TITLE
Label color property -> hex missing?

### ISSUE THREAD

**Issue by zkanda** [kivy/kivy#2547]
Maybe I just don't know how to do it, but I can't find any properties for hex.

```
canvas.before:
    Color:
        hex_color: "#fff"
    Rectangle:
        pos: self.pos
        size: self.size
```
