### ISSUE TITLE
VideoPlayer widget not working on v1.8.0 when part of a ScreenManager stack.

### ISSUE THREAD

**Issue by gelstudios** [kivy/kivy#2632]
VideoPlayer widget works when invoked directly from the terminal (python -m kivy.uix.videoplayer /path/to/file/1.mpg), as a root widget or as a child to a root widget. It does not work when part of a ScreenManager stack, no errors reported in the console. Platform is mac os 10.9.5.

excerpt from .py file:

```
def build(self):
    sm = ScreenManager()
    sm.add_widget(VideoScreen(name='video'))
    return sm
```

from .kv file:

```
<VideoScreen>:
    VideoPlayer:
             source: '/path/to/file/1.mpg'
             state: 'stop'
             allow_stretch: True
```

---

Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/5695073-videoplayer-widget-not-working-on-v1-8-0-when-part-of-a-screenmanager-stack?utm_campaign=plugin&utm_content=tracker%2F42681&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F42681&utm_medium=issues&utm_source=github).
</bountysource-plugin>
