### ISSUE TITLE
[1.8.1] Canvas stencil instructions issue on ScrollView; possibly not discarding old stencil masks?

### ISSUE THREAD

**Issue by SenshiSentou** [kivy/kivy#2635]
This took me quite a while to find the cause of, but it seems canvas stencil instructions break down when used on a widget within a ScrollView.

I created a self-contained example project[1] that demonstrates this behavior. Each `PersistentImageToggleButton` draws a texture within itself, as described in `stencilbug.kv`. The top row (Texture) loads in fully opaque images, while I assigned some partially transparent ones to the bottom row (Overlays) for extra clarity.

The "Overlay" row's textures are drawn on top of the "Texture" row's ones, despite their stencil masks having been popped. Having the main widget extend from a `GridLayout` rather than a `ScrollView` by replacing line 74 with 75 in `main.py` fixes this issue.

[1] https://dl.dropboxusercontent.com/u/971175/Kivy/StencilBug.zip

Is this a known/ expected behavior? I'd like to refrain from having to crop the textures beforehand and all that jazz, so any help/ solution would be much appreciated. =)

On a sidenote, I noticed the docs are on version 1.9 already, while the downloads are still on 1.8. Is 1.9 is a thusly stable state that I should upgrade yet?

**Comment by SenshiSentou** [comment]
Just came across this again and would like to update:

It seems that this only happens for widgets of the same type. Replacing one of the rows with `PersistentImageToggleButton2`s seems to fix the issue. This can be as simple as:

    class PersistentImageToggleButton2(PersistentImageToggleButton):
        pass

**Comment by SenshiSentou** [comment]
I'm not sure why, but the previously mentioned work-around has stopped working for me. Looking at it some more, the problem appears to be due to the nested stencil from the ScrollView (scrollview stencil -> custom stencil).

I'm not sure yet what the best workaround for this is however.

**Comment by kived** [comment]
From the docs: "Changed in version 1.3.0: The stencil operation has been updated to resolve some issues that appeared when nested. You must now have a StencilUnUse and repeat the same operation as you did after StencilPush."

Your code appears to work properly if stencilbug.kv is changed as follows:

````
<PersistentImageToggleButton>:
    canvas:
        Color:
            rgba: (1, 1, 1, 1)

        StencilPush

        Rectangle:
            pos: [self.pos[0] + (self.size[0]*0.15)/2, self.pos[1] + (self.size[1]*0.15)/2 + 1]
            size: [self.size[0]*0.85, self.size[1]*0.85]

        StencilUse

        Rectangle:
            texture: self.tex
            pos: [self.pos[0] + (self.size[0]*0.15)/2, self.pos[1] + (self.size[1]*0.15)/2 + 1] if self.stretchTexture else [self.pos$
            size: [self.size[0]*0.85, self.size[1]*0.85] if self.stretchTexture else self.tex.size

        StencilUnUse

        # this instruction copied from StencilPush above
        Rectangle:
            pos: [self.pos[0] + (self.size[0]*0.15)/2, self.pos[1] + (self.size[1]*0.15)/2 + 1]
            size: [self.size[0]*0.85, self.size[1]*0.85]

        StencilPop
````
