### ISSUE TITLE
[KEP] Selectors in Kv language

### ISSUE THREAD

**Issue by depau** [kivy/kivy#2727]
In kv it's easy to style all the widgets of the same class, but what if I want to change only _one_ property of _that one_ widget which is the grandchild of another widget?
You'd have to rewrite the whole thing changing only _that one_ property.

Let's say you have this:

```
<MyBoxLayout>:
    orientation: "vertical"
    Button:
        Image:
            source: "some_hardcoded_image.png"
```

You only want to change the source of the image. In CSS that would be easy. If you have a _div_ with class _foo_ that contains another _div_, that contains a link of which you want to change the style, you'd something like this:

``` css
.foo div a {
    link: style;
}
```

This is my syntax proposal for a similar feature in the Kv language:

```
<MyBoxLayout Button Image>:
    source: "some_other_image.png"
```

This syntax would indicate that _all_ the Images that are in a Button that is in a MyBoxLayout will have that property overridden.

Another way to select a specific widget over another is the id. Let's say we have this kv:

```
BoxLayout:
    id: mybox
    Image:
        id: image1
        source: "image1.png"
    Image:
        id: image2
        source: "image2.png"

Image:
    id: image3
    source: "image3.jpg"
```

You want to edit _only_ the image with id _image3_. This syntax should be available (it's obvious that this way you can rewrite the kv as it's only one widget, but let's say you previously used <Image> to override the properties of all the Image classes and you want to change only one specific Image, without creating a new class that inherits from it):

```
<Image#image3>:
    property: "value"
```

or you want to edit _image2_ without touching _image1_

```
<Image#image2>:
    property: value
```

or, with the previous syntax, also

```
<BoxLayout Image#image2>:
    prop: value
```

or, if you have multiple boxlayouts and want to edit only one of it:

```
<BoxLayout#mybox Image#image2>:
   property: value
```

for all the images in that box:

```
<BoxLayout#mybox Image>:
   property: value
```
##
