### ISSUE TITLE
Label text color: and markup

### ISSUE THREAD

**Issue by Cheaterman** [kivy/kivy#3290]
Hello,

It appears that color: (0, 0, 1, 1) in KVLang doesn't work on a Label which uses markup.

Thanks for reading!

**Comment by dessant** [comment]
I cannot reproduce this with:

```
    Label:
        text: '[color=#fffff]aaa[/color]ccc'
        color: (0, 0, 1, 1)
        markup: True
```

Any hints?

**Comment by kived** [comment]
````
BoxLayout:
    ToggleButton:
        id: tog
        text: 'Toggle Me'
    Label:
        text: 'hello'
        markup: True
        color: (1, 1, 1, 1) if(tog.state == 'normal') else (0, 0, 1, 1)
````

Workaround is to put the color in the markup:
````
        text: '[color=%s]hello[/color]' % get_hex_from_color(self.color)
````
