### ISSUE TITLE
Widget color "inherited" by another widget

### ISSUE THREAD

**Issue by zuo** [kivy/kivy#3314]
I have no idea why does it happen, but it does. The easiest way to explain it -- is to reproduce it:

```bash
$ git clone git@github.com:tomekd789/brownian-rocket.git
$ cd brownian-rocket
$ git checkout 9b600ac18ec7117b5dc247246187ba13b8ca7a71
$ $ patch -p1 << EOF
diff --git a/rocket.kv b/rocket.kv
index 092597d..8698c1f 100644
--- a/rocket.kv
+++ b/rocket.kv
@@ -13,14 +13,14 @@
         center: self.parent.center

     Label:
-        color: (1, 1, 1, 1)
+        color: (1, 0, 0, 1)
         font_size: 20
         center_x: root.width - 50
         top: root.top + 40
         text: "Czas: " + str(round(root.timer))

     Label:
-        color: (1, 1, 1, 1)
+        color: (1, 0, 0, 1)
         font_size: 20
         center_x: 50
         top: root.top + 40
EOF
$ python3.4 Rocket.kv
```
...and everything is OK.

But when I change the order of widgets within the GameWidget -- moving the Rocket widget below the Label widgets...

```bash
$ patch -p1 << EOF
diff --git a/rocket.kv b/rocket.kv
index 8698c1f..65f308c 100644
--- a/rocket.kv
+++ b/rocket.kv
@@ -8,9 +8,6 @@
             pos: self.pos

     rocket: game_rocket
-    Rocket:
-        id: game_rocket
-        center: self.parent.center

     Label:
         color: (1, 0, 0, 1)
@@ -26,6 +23,10 @@
         top: root.top + 40
         text: "Punkty: " + str(root.score)

+    Rocket:
+        id: game_rocket
+        center: self.parent.center
+
 <Rocket>:
     size: 43, 93
     canvas:
EOF
```

...the Rocket becomes red -- that is, somehow "inherits" the color from the labels!

```bash
$ python3.4 Rocket.kv
```

I tried debugging the process of kv parsing but it seems to be OK (the "Rocket" rule does not have the "color" property; it has only its own "center" property).

It seems to me very strange.

* Linux
* Python 3.4.0
* pip freeze:
```
Cython==0.21.2
Kivy==1.9.0
Kivy-Garden==0.1.1
pygame==1.9.2a0
requests==2.6.2
```

**Comment by kived** [comment]
This is expected behavior. We don't automatically set the drawing color to anything. In the `Rocket` widget kv, you need to set the color with a `Color` instruction before drawing anything.

````
<Rocket>:
    size: 43, 93
    canvas:
        # add the following two lines
        Color:
            rgba: 1, 1, 1, 1
        #Rotate:
        #    angle: 45
        #    axis: 0, 0, 1
        Rectangle:
            source: "Images/Rocket.gif"
            pos: self.pos
            size: 43, 93
````
