### ISSUE TITLE
kv language : can't overwrite a property set in a rule

### ISSUE THREAD

**Issue by mpad** [kivy/kivy#355]
When a property is set in a kv rule, then this property can't be overwritten by instances of the rule in the rest of the kv file.

Example:

```
<Label>:
    color: [1,0,0,1] # red
<MyWidget>:
    Label:
        text: 'BLA'
    Label:
        color: 0,0,1,1 # blue
        text: 'BLA again'
```

The setting of color for the 2nd label is completely ignored : both labels are red when the 2nd is expected to be blue.
