### ISSUE TITLE
Sometimes not redrawing, after setting slider.value

### ISSUE THREAD

**Issue by stuaxo** [kivy/kivy#3623]
I've made something to emulate an APC Mini 

apc mini:
http://music.stackexchange.com/questions/28864/akai-apc-mini-compatibility-with-fl-studio

screenshot of my kivy app:
http://imgur.com/t8XUh3d

python code:
https://gist.github.com/stuaxo/e774a65e57e36b30e784

It uses midi to move the sliders on the kivy app from the real thing, by setting  `slider.value`.

If I move the slider on the real thing very fast, to the top or bottom, a lot of the time it will go not quite all the way.    

If I trigger a redraw (say by pressing a button at the top, using the mouse or the real thing) - then the slider moves to the right place.

**Comment by janssen** [comment]
Yes, I see this too.  Using 1.9.1 stable.

**Comment by janssen** [comment]
By the way, this is intermittent for me.  Sometimes it updates, sometimes it doesn't.

**Comment by janssen** [comment]
Almost seems like a daemon thread is dying.  The connection between the value and the cursor position is done in kivy/data/style.kv:
```
        Rectangle:
            pos: (self.value_pos[0] - sp(16), self.center_y - sp(17)) if self.orientation == 'horizontal' else (self.center_x - (16), self.value_pos[1] - sp(16))
            size: (sp(32), sp(32))
            source: 'atlas://data/images/defaulttheme/slider_cursor{}'.format('_disabled' if self.disabled else '')
```
and `value_pos` is updated by code in kivy/uix/slider.py.  I don't know how the lang module attaches the two, but if it's a daemon thread, that could be dying.
