### ISSUE TITLE
Recommendation: Expose bar_width and scroll_type for ListView

### ISSUE THREAD

**Issue by ngoonee** [kivy/kivy#3658]
Please refer this forum topic - https://groups.google.com/forum/#!topic/kivy-users/iiNImVlGzJY

I recommend exposing bar_width (as NumericProperty) and scroll_type (as OptionProperty) in ListView, while binding the ScrollView in ListView's definition to them. Please see example below.

Conceptual (doesn't work, I'm not sure how to make it work):-
```
<ListView>:
    container: container
    bar_width: <somedefaultvalue>
    scroll_type: <somedefaultvalue>
    ScrollView:
        pos: root.pos
        on_scroll_y: root._scroll(args[1])
        do_scroll_x: False
        bar_width: root.bar_width
        scroll_type: root.scroll_type
        GridLayout:
            cols: 1
            id: container
            size_hint_y: None
```

Benefit is we can easily get ListViews which support grab-bable scroll bars, something quite important in desktop usage.
