### ISSUE TITLE
Extend Accordion widget functionality/behavior in Kivy

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/kivy#3702]
as mentioned in the title i need to add custom behavior to an AccorditionItem. I've tried to change the _title_template_ with a custom one where i placed an _on_press_ event inside it that print something on screen inplemented like the following code:

```
[ExtendedItemTitle@Label+Button]:
    text: ctx.title
    canvas.before:
        Color:
            rgb: 1, 1, 1
        BorderImage:
            source:
                ctx.item.background_normal \
                if ctx.item.collapse \
                else ctx.item.background_selected
            pos: self.pos
            size: self.size
        PushMatrix
        Translate:
            xy: self.center_x, self.center_y
        Rotate:
            angle: 90 if ctx.item.orientation == 'horizontal' else 0
            axis: 0, 0, 1
        Translate:
            xy: -self.center_x, -self.center_y
    canvas.after:
        PopMatrix
    on_press: print("accordition pressed")

BoxLayout:
    id: MainContainer
    orientation: "vertical"
    Accordion:
        id: MainAccordion
        orientation: "vertical"     
        AccordionItem:
            id: DataItem    
            title: "Data Setup"
            title_template: "ExtendedItemTitle"
            collapse: False
            BoxLayout:
        AccordionItem:
            id: ElaborateItem
            title: "ELABORATE!"
            title_template: "ExtendedItemTitle"
            BoxLayout:
```

but it does not work as I expected, because when an item is clicked for the first time the _on_press_ event do not start, but starts only when the menu item is already open and is clicked for the second time. Basically what I'm trying to do is to call another function which starts after the default behavior. Thus the basic accordion's behavior (open and close the menus) should not be changed. I only need to add a button's like behavior (or a toggle-button behavior).

How can i accomplish that?

Thanks in advance for your replies
