### ISSUE TITLE
problem using Video and Camera at the same time

### ISSUE THREAD

**Issue by pigant** [kivy/kivy#3848]
First, sorry for my English
I have tried to put a Video and Camera widget in a ScreenManager, but when i put them in that order
my program crash
i'm using Debian jessie, and i have no problem using these separated

```
<Siguiente@Button>:
text: 's'
    size_hint: .1, .1
    pos_hint:  {'right': 1}

ScreenManager:
    Screen:
        name: 'video'
        Video:
            source: 'video.mp4'
            options: {'eos':'loop'}
            play: True
        Siguiente:
            on_press: root.current = 'camara'
    Screen:
        name: 'camara'
        Camera:
            play: True
            resolution: (640, 480)
            pos_hint: {'right': 1}
        Siguiente:
            on_press: root.current = 'video'
```

The log is this:

```
 /usr/lib/python2.7/dist-packages/kivy/core/video/video_gstplayer.py:67: Warning: cannot register existing type 'GstObject'
   self._on_gst_eos_sync, _on_gstplayer_message)
 /usr/lib/python2.7/dist-packages/kivy/core/video/video_gstplayer.py:67: Warning: g_once_init_leave: assertion 'result != 0' failed
   self._on_gst_eos_sync, _on_gstplayer_message)
 /usr/lib/python2.7/dist-packages/kivy/core/video/video_gstplayer.py:67: Warning: g_type_register_static: assertion 'parent_type > 0' failed
   self._on_gst_eos_sync, _on_gstplayer_message)
 /usr/lib/python2.7/dist-packages/kivy/core/video/video_gstplayer.py:67: Warning: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
   self._on_gst_eos_sync, _on_gstplayer_message)

(main.py:4324): GStreamer-CRITICAL **: gst_object_ref: assertion 'object != NULL' failed

(main.py:4324): GStreamer-CRITICAL **: gst_allocator_register: assertion 'allocator != NULL' failed

(main.py:4324): GStreamer-CRITICAL **: gst_object_ref: assertion 'object != NULL' failed
 /usr/lib/python2.7/dist-packages/kivy/core/video/video_gstplayer.py:67: Warning: cannot register existing type 'GstFormat'
   self._on_gst_eos_sync, _on_gstplayer_message)
 /usr/lib/python2.7/dist-packages/kivy/core/video/video_gstplayer.py:67: Warning: cannot retrieve class for invalid (unclassed) type '<invalid>'
 Exception in thread Thread-1:
   self._on_gst_eos_sync, _on_gstplayer_message)
 Traceback (most recent call last):
 /usr/lib/python2.7/dist-packages/kivy/core/video/video_gstplayer.py:67: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
   self._on_gst_eos_sync, _on_gstplayer_message)
     self.run()
```
