### ISSUE TITLE
Maybe a bug in ScreenManager.switch_to()

### ISSUE THREAD

**Issue by youpsla** [kivy/kivy#3924]
As far I understand the doc, the switch_to() method should remove the old_screen widget from the screens list.

I've done a test

```
main.py
# -*- coding: utf-8 -*-
from kivy.app import App
from kivy.uix.screenmanager import ScreenManager, Screen


class Sm(ScreenManager):
    pass

    # def __init__(self, **kwargs):
    #     self.switch_to(Screen1())
    #     super(Sm, self).__init__(**kwargs)


class Screen1(Screen):
    pass


class Screen2(Screen):
    pass


class MainApp(App):
    pass


if __name__ == '__main__':
    MainApp().run()
```
```
main.kv

#: import main main
#: import FadeTransition kivy.uix.screenmanager.FadeTransition


Sm:
    transition: FadeTransition()
    Screen1:
        name: 'screen1'
    # Screen2:
    #     name: 'screen2'

<Screen1>:
    # name: 'screen1'
    Label:
        size_hint_y: 0.8
        text: 'Screen one'
    Button:
        size_hint_y: 0.2
        text: "To screen 2"
        on_release: app.root.switch_to(main.Screen2())


<Screen2>:
    name: 'screen2'
    Label:
        size_hint_y: 0.8
        id: lbl
        text:'screen two'
    Button:
        size_hint_y: 0.2
        text: "To screen 1"
        on_release: app.root.switch_to(main.Screen1())
```

And here is the output of 'print "Screens in ScreenManager.switch_to : ", self.current_screen' put in line 1040 of screenmanager.py
```
Screens in ScreenManager.switch_to :  <Screen name='screen1'>
Screens in ScreenManager.switch_to :  <Screen name='screen2'>
Screens in ScreenManager.switch_to :  <Screen name=''>
Screens in ScreenManager.switch_to :  <Screen name='_screen0'>
Screens in ScreenManager.switch_to :  <Screen name='_screen1'>
Screens in ScreenManager.switch_to :  <Screen name='_screen2'>
Screens in ScreenManager.switch_to :  <Screen name='_screen3'>
Screens in ScreenManager.switch_to :  <Screen name='_screen4'>
...
```
Changing (https://github.com/kivy/kivy/blob/master/kivy/uix/screenmanager.py#L1043) "if old_current in self.children:" to "if old_current in self.screens:" will ouput:
```
Screens in ScreenManager.switch_to :  <Screen name='screen1'>
Screens in ScreenManager.switch_to :  <Screen name='screen2'>
Screens in ScreenManager.switch_to :  <Screen name='screen1'>
Screens in ScreenManager.switch_to :  <Screen name='screen2'>
Screens in ScreenManager.switch_to :  <Screen name='screen1'>
Screens in ScreenManager.switch_to :  <Screen name='screen2'>
...
```
which i think is the good output.

Am I right ?
