### ISSUE TITLE
ActionBar: ActionView layout more dense/packed after increase of width

### ISSUE THREAD

**Issue by AndiEcker** [kivy/kivy#4119]
Increasing the `width` of the `ActionBar` after the first layout done on app startup (e.g. by resizing the window on the linux desktop or after changing the orientation of an android app from portrait to landscape) results in a different (even more packed) layout.

The following code - taken from the test section on the end of kivy's actionbar.py - demonstrates the problem (simply resize the window on the desktop or press the `ActionButton` labeled as Btn1):

```
import kivy
from kivy.base import runTouchApp, Builder
from kivy.uix.floatlayout import FloatLayout
from kivy.factory import Factory

Builder.load_string('''
<MainWindow>:
    ActionBar:
        id: actBar
        pos_hint: {'top':1}
        ActionView:
            use_separator: True
            ActionPrevious:
                title: 'Action Bar - CHANGE KIVY WINDOW WIDTH to demonstrate bug'
                with_previous: False
            ActionOverflow:
            ActionButton:
                text: 'Btn0'
                icon: 'atlas://data/images/defaulttheme/audio-volume-high'
            ActionButton:
                text: 'Btn1'
                on_release: actBar.width = actBar.width + 1
            ActionButton:
                text: 'Btn2'
            ActionGroup:
                text: 'Group 2'
                ActionButton:
                    text: 'Btn3'
                ActionButton:
                    text: 'Btn4'
            ActionGroup:
                text: 'Group1'
                ActionButton:
                    text: 'Btn5'
                ActionButton:
                    text: 'Btn6'
                ActionButton:
                    text: 'Btn7'
''')

class MainWindow(FloatLayout):
    pass


if __name__ == "__main__":
    float_layout = MainWindow()
    runTouchApp(float_layout)
```
The problem is that the `width` property value of the `ActionPrevious` widget will not be reset/recalculated on change of the `ActionBar` `width`, and the `pack_width` property of the `ActionPrevious` (inherited from `ActionItem`) will always use the last calculated `width` value.

Overwriting the `pack_width` property of `ActionPrevious` to ignore the current `width` (only checking for the `minimum_width`) by adding the following code lines directly in the `ActionPrevious` class fixes it, but I am not sure if there is not a better way or if this fix is breaking existing functionality:

```
    def get_pack_width(self):
        return self.minimum_width
    pack_width = AliasProperty(get_pack_width, bind=('minimum_width', 'width'))
```

The problem not existed in kivy 1.8 and did possibly came up with the fix of #3500 (see commit in #3871).
