### ISSUE TITLE
Issue with PageLayout nested in another layout

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/kivy#4330]
The pageLayout is in a wrong position when the app is started. If i swip a page (moving the mouse in the position where the pagelayout should be) automatically the content is relocated to the right area of the screen. 

A simple test code that give me the problem:

```
	BoxLayout:
		BoxLayout:
			size_hint_y: .08	
			orientation: "horizontal"				
			AnchorLayout:
				anchor_x: "center"
				BoxLayout:	
					size_hint_x: None
					width: dp(350)
					Label:
                                               text: "text"
					Label:
						text: "text2"
						text_size: self.size
						font_size: 18
						markup: True
						halign: "left"
						valign: "middle"				
		BoxLayout:
			PageLayout:
				BoxLayout:
                                        orientation: "horizontal"				
					Label: 
						text: "text3"	
				BoxLayout:
                                        orientation: "horizontal"	
					Label: 
						text: "text4"	
				BoxLayout:
                                        orientation: "horizontal"	
					Label: 
						text: "text5"	
		BoxLayout:
			size_hint_y: .15
			BoxLayout:
				BoxLayout:
                                        orientation: "horizontal"	
					BoxLayout:
                                                orientation: "horizontal"	
						Label:
							text: "text6"
					BoxLayout:
                                                orientation: "horizontal"	
						size_hint_y: .3
						Label:
							text: "text7"
				BoxLayout:
					size_hint_x: .1
					Button:			
						text: "text8"
```

Is an issue or there is a trick to make it work on startup?

thanks
