### ISSUE TITLE
TextInput does not lose focus inside ScrollView

### ISSUE THREAD

**Issue by Fak3** [kivy/kivy#4399]
Hi. I found the issue with behavior of TextInput focus inside ScrollView. If i touch other widget - TextInput does not lose focus despite the property unfocus_on_touch: True.

Sample program:
```
<ScrollView>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'lol'
        TextInput:
            text: 'Hello World'
```
When I click on the Label, Textinput does not lose focus. But If I remove ScrollView from code - it works as intended.
