### ISSUE TITLE
Scatter rotation removes/adds widget

### ISSUE THREAD

**Issue by duelafn** [kivy/kivy#442]
Kivy v1.2.0: If I rotate a scatter, it appears to be removed then re-added to its parent. If the scatter is part of a BoxLayout, this will cause the scatter to move to the end of the Layout. In the sample below, clicking "Rotate 1" will rotate the scatter but also swap the positions of 1 and 2. This is true whenever you rotate the top scatter.

Sample .kv (runs with kvrun.py):

```
#:kivy 1.0
BoxLayout:
    orientation: "vertical"

    Scatter:
        Button:
            text: "Rotate 1"
            on_press: self.parent.rotation = (180 + self.parent.rotation) % 360

    Scatter:
        Button:
            text: "Rotate 2"
            on_press: self.parent.rotation = (180 + self.parent.rotation) % 360
```
