### ISSUE TITLE
TabbedPanel.switch_to() does not scroll to the tab

### ISSUE THREAD

**Issue by Philbsp** [kivy/kivy#4495]
When using TabbedPanel.switch_to(tab) the tab's content is shown correctly and the tab is selected, however if the tab is not on the screen it is not scrolled to. 

Thanks!

**Comment by KeyWeeUsr** [comment]
```
from kivy.lang import Builder
from kivy.base import runTouchApp
from kivy.uix.boxlayout import BoxLayout
Builder.load_string('''
<Test>:
    ScreenManager:
        id: man
        Screen:
            BoxLayout:
                Button:
                    text: 'next screen'
                    on_release: man.current = 'scr'
                Button:
                    text: 'next screen & switch_to'
                    on_release: root.scroll(man, panel, last)
        Screen:
            name: 'scr'
            TabbedPanel:
                do_default_tab: False
                id: panel
                TabbedPanelItem:
                    Button:
                        text: 'to last'
                        on_release: panel.switch_to(last, do_scroll=True)
                TabbedPanelItem:
                    Label:
                        text: 'one'
                TabbedPanelItem:
                    Label:
                        text: 'one'
                TabbedPanelItem:
                    Label:
                        text: 'one'
                TabbedPanelItem:
                    Label:
                        text: 'one'
                TabbedPanelItem:
                    Label:
                        text: 'one'
                TabbedPanelItem:
                    Label:
                        text: 'one'
                TabbedPanelItem:
                    Label:
                        text: 'one'
                TabbedPanelItem:
                    id: last
                    Label:
                        text: 'last'
''')
class Test(BoxLayout):
    def scroll(self, man, panel, last):
        panel.switch_to(last, do_scroll=True)
        man.current = 'scr'
runTouchApp(Test())
```

Is the `next screen -> to_last` the thing you are talking about, or is it the behavior in `scroll(man, panel, last)` function? If it's the first, then https://github.com/kivy/kivy/pull/4559 however I don't have a clue how to fix the second issue. It's probably because of a different screen, so ScrollView kind of ignores everything or what.
