### ISSUE TITLE
kivy.uix.videoplayer attempts to load source path as Image when loading file

### ISSUE THREAD

**Issue by Bakterija** [kivy/kivy#4535]

**Comment by dessant** [comment]
This seems to happen because Video is subclassed from Image, so when setting Video.source, the loading logic of Image is also executed.

**Comment by rayrase** [comment]
I'm new to open source and feel this is something I can fix. Is this issue still up for grabs?

**Comment by dessant** [comment]
@rayrase, yes, of course.

**Comment by rayrase** [comment]
Ok, thank you!

**Comment by BittaBoesaBiba** [comment]
Same issue here. Can be reproduced with `Video` and `VideoPlayer` respectively

```
Screen:
    Video:  # or VideoPlayer
        size_hint: None, None
        size: dp(640), dp(380)

        # https://sample-videos.com/video321/mp4/360/big_buck_bunny_360p_1mb.mp4
        source: 'big_buck_bunny_360p_1mb.mp4'
        on_touch_up: self.state = 'play'
```

Fix would be to adjust `__init__` like
```
    def __init__(self, **kwargs):
        self._video = None
        self.source = kwargs.pop('source')  # <----- this
        super(Video, self).__init__(**kwargs)
        self.fbind('source', self._trigger_video_load)

        if "eos" in kwargs:
            self.options["eos"] = kwargs["eos"]
        if self.source:
            self._trigger_video_load()
```

For now one could override the init in a subclass.
```
from kivy.uix.video import Video
class GentleVideo(Video):
    """Prevents warning
    Image: Error loading <path/to/file.mp4>
    """
    def __init__(self, **kwargs):
        self._video = None
        self.source = kwargs.pop('source')
        super(Video, self).__init__(**kwargs)
        self.fbind('source', self._trigger_video_load)

        if "eos" in kwargs:
            self.options["eos"] = kwargs["eos"]
        if self.source:
            self._trigger_video_load()
```

I'll see if I can quickly create a pull request.
