### ISSUE TITLE
Make Color-object compatible with more common formats

### ISSUE THREAD

**Issue by NSasquatch** [kivy/kivy#4576]
Most tools I use display color in 255 or hex format by default. It would be really useful if that could be used directly. 

```
Color:
    rgb: 1, 0.1, 1
    rgba: 1., 0.1, 0.5, 0.3
    rgb255: 47, 25, 64
    rgba255: 222, 13, 135, 190
    hex: 0x00ff00
```
