### ISSUE TITLE
Builder.load_file error

### ISSUE THREAD

**Issue by kivyuser1** [kivy/kivy#4681]
The following code causes two different issues, where functionality is not as expected.

My tmp.py Kivy App is supposed to draw a green rectangle and a button.
Pressing the button should print the children of the root which is a list with a single element (the button).

Issue 1: If ran as is, the rectangle is white instead of green. 
Issue 2: If the line #Builder.load_file('tmp.kv') is uncommented then the rectangle is indeed green, but this causes a new issue: pressing the button prints a list of length 2 instead of 1.

file tmp.kv:
```
<M>:
    canvas.before:
        Rectangle:
            size: (500,500) #self.size
            pos: (100,100)
        Color:
            rgba: 0, 1, 0, 1              
    Button:
        on_press: print self.parent.children   
```     

File tmp.py:
```
import kivy
kivy.require('1.0.7')

from kivy.app import App
from kivy.lang import Builder
from kivy.uix.widget import Widget
from kivy.uix.button import Button
from kivy.graphics import Color, Rectangle, Canvas
from kivy.base import runTouchApp

#Builder.load_file('tmp.kv')

class M(Widget):
      pass  
                    
class TmpApp(App):
    def build(self):
        m= M()
        return m

if __name__ == '__main__':
    TmpApp().run()

```

I run the code from command line: 
$python tmp.py

**Comment by KeyWeeUsr** [comment]
I think it's probably because of the `Color` used after the `Rectangle` (which shouldn't be) and it does exactly that - draws `Rectangle` with the default `Color`(white) and then it changes it to green (not the whole canvas content).
About the second one, the `kv` file is already loaded and you reload it once again, so something got messed up. Maybe there were two buttons added at the same place or something. It's not an issue, it's badly used `kv` file and instructions.

**Comment by Kovak** [comment]
kv files are more like CSS, so loading one file twice is basically like saying:

```
<M>:
    canvas.before:
        Rectangle:
            size: (500,500) #self.size
            pos: (100,100)
        Color:
            rgba: 0, 1, 0, 1
        Rectangle:
            size: (500,500) #self.size
            pos: (100,100)
        Color:
            rgba: 0, 1, 0, 1                
    Button:
        on_press: print self.parent.children  
    Button:
        on_press: print self.parent.children 
```
