### ISSUE TITLE
Examples: canvas/line.py

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#5001]
### Versions

* Python: 2.7, 3.5
* OS: Win8.1, 64bit
* Kivy: master, wheels

### Description

Doesn't change any of the cap/joint values, but it works with an ordinary kv file:

```
from kivy.app import runTouchApp
from kivy.lang import Builder
runTouchApp(Builder.load_string('''
Widget:
    canvas:
        Color:
            rgb: 1,0,0
        Line:
            width: 5
            points: [100,100,250,170,300,50]
            joint: 'none'
            cap: 'square'
            close: False
'''))
```
