### ISSUE TITLE
Nested Templates support

### ISSUE THREAD

**Issue by gau-veldt** [kivy/kivy#513]
It would appear kivy's .kv cannot do nested templates such as:

```
height: 24
#...other numerous property settings...
text: ctx.text


decoratedlabel:
    text: ctx.field['name']
decoratedlabel:
    text: ctx.field['path']
...more result fields...
```

The idea would be, say after running a query, to instantiate a resultrowtemplate on each dbapi result row.

The latter definitions under decoratedlabel complain about KeyError on ctx

Sure I can work around it by duplicating all the settings of decoratedlabel out for each result field (label: ...) but this is not only tedious, it is very un-DRY

could this functionality be added to future kivy?
