### ISSUE TITLE
Rendering artifact with scaled textures

### ISSUE THREAD

**Issue by bionoid** [kivy/kivy#5261]
### Versions

* Python: 3.6.1
* OS: Tested on Ubuntu 16.04 and Win7pro
* Kivy: 1.10
* Kivy installation method: pip

### Description

A rendering artifact appears when image textures are scaled. This test case is two 100x100 PNGs, when overlaid they align to fill the 100x100 pixels exactly. This works as expected when not scaling, but with scaling there is an unexpected artifact.

* [Rendering artifact when scaled down](http://i.imgur.com/O52e1IJ.png)
* [Rendering artifact when scaled up](http://i.imgur.com/x4cEE0m.png)
* [On yellow background](http://i.imgur.com/uMObDsK.png) to demonstrate that it's not transparency

### Code and Logs

The below examples reproduce the issue on my systems using different approaches.

#### Example 1

```python
from kivy.base import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string('''
FloatLayout:
    AsyncImage:
        source: 'http://i.imgur.com/KKva3Os.png'
        allow_stretch: True
    AsyncImage:
        source: 'http://i.imgur.com/ILBfKkJ.png'
        allow_stretch: True
'''))
```

#### Example 2

This is correct on load, not when scaled

```python
from kivy.base import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string('''
Scatter:
    size_hint: None, None
    FloatLayout:
        AsyncImage:
            source: 'http://i.imgur.com/KKva3Os.png'
        AsyncImage:
            source: 'http://i.imgur.com/ILBfKkJ.png'
'''))
```

#### Example 3

This is correct on load, not when scaled

```python
from kivy.app import App
from kivy.lang import Builder
from kivy.loader import Loader

KV = '''
Scatter:
    tx1: None
    tx2: None
    size_hint: None, None
    canvas:
        Rectangle:
            texture: self.tx1
            size: self.size
        Rectangle:
            texture: self.tx2
            size: self.size        
'''

class TestApp(App):
    def build(self):
        def handler1(proxy):
            setattr(self.root, 'tx1', proxy.image.texture)
        def handler2(proxy):
            setattr(self.root, 'tx2', proxy.image.texture)

        img1 = Loader.image('http://i.imgur.com/KKva3Os.png')
        img1.bind(on_load=handler1)

        img2 = Loader.image('http://i.imgur.com/ILBfKkJ.png')
        img2.bind(on_load=handler2)

        return Builder.load_string(KV)

TestApp().run()
```

**Comment by tito** [comment]
I think it is the same kind of issue that beginner have when scaling down/up image with opacity. The opacity layer is also stretched, and leads to issue with transparency;
One way to test is in your case, both of your picture should have RGB full red, and A only partially filled with white, the rest with black. Then when OpenGL will stretch the image, the opacity layer (A) will be blended (from black to white in the middle) and the base color will be the red; otherwise it will be black if you don't have any information, that's where the glitch happen.

**Comment by tito** [comment]
Weird. The blending always happen with black. I changed both of your image to have one image with full blue, and only half transparent on the bottom, and the other with red and half transparent to the top. I double-checked that the PNG itself does have correctly the blue and red on the transparent part. But it doesn't solve the issue O_o. Also checked with SDL2 or ImageIO (osx) provider.

Just one half image give this when scaled:
<img width="912" alt="capture d ecran 2017-07-13 a 15 34 31" src="https://user-images.githubusercontent.com/37904/28168974-1c15b8d4-67e1-11e7-88e5-011743a0743c.png">

And for informations, this is the sources images:
![kkva3os](https://user-images.githubusercontent.com/37904/28168982-234f8576-67e1-11e7-957e-4edeab36e9a3.png)
![ilbfkkj](https://user-images.githubusercontent.com/37904/28168983-236f480c-67e1-11e7-9ebb-3b538c54c765.png)

And source code:
```
from kivy.base import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string('''

FloatLayout:
    canvas.before:
        Color:
            rgba: 0, 1, 0, 1
        Rectangle:
            pos: 0, 0
            size: self.size
    
    Scatter:
        size_hint: None, None
        canvas.before:
            Color:
                rgba: 0, 1, 0, 1
            Rectangle:
                pos: 0, 0
                size: self.size
        FloatLayout:
            Image:
                source: '/Users/tito/Downloads/KKva3Os.png'
            #Image:
            #    source: '/Users/tito/Downloads/ILBfKkJ.png'
'''))
```
