### ISSUE TITLE
inspector not working in kivy-1.10.0 Popup

### ISSUE THREAD

**Issue by rjungbeck** [kivy/kivy#5369]
Opening inspector (Ctrl+E) on a Popup window shows the fields from the underlying window (and not from the Popup). 

This makes using inspector on Popups (which could be the bigger part of an application) impossible.

**Comment by bionoid** [comment]
I cannot reproduce this on Windows, can you be more specific about the context in which this fails? I tested with this code:

```python
from kivy.base import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string('''
#:import F kivy.factory.Factory

<TestPopup@Popup>:
	size_hint: .5, .5
	Button:
		on_press: root.dismiss()

Button:
	on_press: F.TestPopup().open()
'''))
```

**Comment by rjungbeck** [comment]
The context is a bit more complicated:

`````
from kivy.base import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string('''
#:import F kivy.factory.Factory


<TestPopup2@Popup>:
    title: "test2"
    size: 300, 300
    size_hint: None, None
    Button:
        size: 100, 100
        size_hint: None, None
        on_press: root.dismiss()
        
<TestPopup@Popup>:
    title: "test"
    size: 300, 300
    size_hint: None, None
    Button:
        size: 200, 200
        size_hint: None, None
        on_press: F.TestPopup2().open()

BoxLayout:
    size: 800,480
    size_hint: None, None

    Label:
        size: 200, 500
        size_hint: None, None
        text: "Root"
        
    Button:
        size: 200, 500
        size_hint: None, None
        on_release: F.TestPopup().open()
    
    
    '''))

`````
Try to activate the inspector on the button on the second popup (where the button overlap with the underlaying popups button)  It activates the wrong field..

(Test on Mac)
