### ISSUE TITLE
Window doesn't seem to size my widgets correctly

### ISSUE THREAD

**Issue by juliansd** [kivy/kivy#5452]
### Versions

* Python: 3
* OS: iOS
* Kivy: 1.10.0
* Kivy installation method: pip

### Description

I used code from an example on youtube, (https://www.youtube.com/watch?v=ZVWAKzR63ig&index=4&list=PLdNh1e1kmiPP4YApJm8ENK2yMlwF1_edq), and when i used the same code the widgets don't size the same way that they do in this tutorial video.  Instead it splits the screen evenly in half for the two widgets.

Here's a screenshot:

<img width="908" alt="screen shot 2017-10-24 at 11 47 38 am" src="https://user-images.githubusercontent.com/24559680/31953468-3af7799c-b8b1-11e7-852b-07b4b3b8696e.png">

If you look in the tutorial video, the top widget's height is only as high as the line of text in the TextInput widget.

Here's my code:

```python

import kivy
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout

kivy.require('1.10.0')


class ScatterTextWidget(BoxLayout):
    pass


class Planner(App):

    def build(self):
        return ScatterTextWidget()

if __name__ == '__main__':
    Planner().run()

```

kv file:

```

#:kivy 1.10.0
<ScatterTextWidget>
    orientation: 'vertical'
    TextInput:
        id: my_textinput
        font_size: 150
        sieze_hint_y: None
        height: 200
        text: 'default'
    FloatLayout:
        Scatter:
            Label:
                text: my_textinput.text
                font_size:150

```
