### ISSUE TITLE
Crash app when load profile picture download from graph.facebook 

### ISSUE THREAD

**Issue by Thong-Tran** [kivy/kivy#6117]
### Versions

* Python: 3.7.1
* OS: Windows 10, MacOS 10.13.6
* Kivy: 1.10.1
* Kivy installation method: pypi

### Description
I download pic via `https://graph.facebook.com/v3.2/me?fields=first_name,last_name,picture,email&access_token={token}` and save pic
```python
r = requests.get(json_graph['picture']['data']['url'], stream=True)
if r.status_code == 200:
    with open(join(self.data_path, 'pro_file_pic.jpg'), 'wb') as f:
          for chunk in r:
               f.write(chunk)
MyWidget()
```
On windows, can't open image but don't crash app.
On Mac, just crash and show.
```
[DEBUG  ] [ImageImageIO] Load </Users/ivc/Library/Application Support/Tetris 2D/pro_file_pic.jpg>
Segmentation fault: 11
```
**But when i reopen app with that file**  (already downloaded in drive before), image load ok in both platform.

Kv file:
```
<MyWidget@Widget>:
    canvas:
        RoundedRectangle:
            pos:self.pos
            size: self.size
            radius: [9000]
            source: join(app.user_data_dir, 'pro_file_pic.jpg') if app.fbAcc.token else 'mgame/data/blank.png'
```
