### ISSUE TITLE
Change ListItemButton height by .kv, 'height' doesn't work but 'size' works

### ISSUE THREAD

**Issue by HowcanoeWang** [kivy/kivy#6241]
# Versions

* Python:  v3.5.4
* OS: Win10
* Kivy: 1.10.1
* Kivy installation method: Pycharm virtualenv

# Description

When I trying to change the height of ListItemButtons in the kv file by `height` attributes
```
height: "60dp"
size_hint_y: None
```

it has no changes, however, if I use `size` attributes
```
size: (100, "60dp")
size_hint_y: None
```
That works!

This problem has posted several years ago, but it seem not been solved until now.
> https://stackoverflow.com/questions/36734799/kivy-listitembutton-how-to-increase-the-height-of-button-size/51292227
> https://groups.google.com/forum/#!topic/kivy-users/e-OhrX6uvSg

# Code and Logs

### Height Attributes doesn't work
*main.py*

```python
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.listview import ListItemButton

class TestRoot(BoxLayout):
    pass

class TestListItemButton(ListItemButton):
    pass

class TestApp(App):
    pass

if __name__ == '__main__':
    TestApp().run()
```

*Test.kv*

```
#: import main main
#: import ListAdapter kivy.adapters.listadapter.ListAdapter

TestRoot:
    orientation: "vertical"
    ListView:
        adapter: ListAdapter(data = ['0','1','2','3','4','5','6','7','8','9'], cls = main.TestListItemButton)

<TestListItemButton>:
    height: '60dp'
    size_hint_y: None
```
![image](https://user-images.githubusercontent.com/19968935/55747624-0cf87a00-5a13-11e9-8a9c-e83b916b640e.png)

---

### Size Attribute works

*main.py*

(not change)

*Test.kv*
```
#: import main main
#: import ListAdapter kivy.adapters.listadapter.ListAdapter

TestRoot:
    orientation: "vertical"
    ListView:
        adapter: ListAdapter(data = ['0','1','2','3','4','5','6','7','8','9'], cls = main.TestListItemButton)

<TestListItemButton>:
    size: (100, "60dp")
    size_hint_y: None
```
![image](https://user-images.githubusercontent.com/19968935/55747758-5a74e700-5a13-11e9-9711-a19fe4426564.png)

---

### It also works if we modify height in py file

*main.py*

```python
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.listview import ListItemButton

class TestRoot(BoxLayout):
    pass

class TestListItemButton(ListItemButton):

    def __init__(self, **kwargs):
        super(TestListItemButton, self).__init__(**kwargs)
        self.height = "60dp"

class TestApp(App):
    pass


if __name__ == '__main__':
    TestApp().run()
```

*Test.kv*

```
#: import main main
#: import ListAdapter kivy.adapters.listadapter.ListAdapter

TestRoot:
    orientation: "vertical"
    ListView:
        adapter: ListAdapter(data = ['0','1','2','3','4','5','6','7','8','9'], cls = main.TestListItemButton)

<TestListItemButton>:
    #size: (100, "60dp")
    #height: '60dp'
    #size_hint_y: None
```
![image](https://user-images.githubusercontent.com/19968935/55747901-b2abe900-5a13-11e9-9364-4cd5af812d0e.png)
