### ISSUE TITLE
kv label zh_ch 

### ISSUE THREAD

**Issue by linpan** [kivy/kivy#6445]
```
            Label:
                text: "北京"
                font_size: 28
                size_hint: 1, .1

```
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 357: ordinal not in range(128)

- python3.6 
- kivy 1.11.1
