### ISSUE TITLE
Label.text asks for string but is getting string

### ISSUE THREAD

**Issue by iustin94** [kivy/kivy#6470]
Hi, I'm having issues with changing the text of Label object that was declared in a kv file.
When I attempt to change the text property of that Label object in it's root constructor, I receive the error Label.text property expects a str value.

The label in question is: 

```
<FlightSummaryScreen>:
    ScrollView:
        size: self.size
        GridLayout:
            cols:1
            Label:
                size_hint: 1, None
                height: 50
                markup: True
                text: '[b]Mission overview:[/b]'
            GridLayout:
                cols: 3
                row_force_default: True
                row_default_height: 45
                Label:
                    size_hint_y : None
                    height: 30
                    text:"Mission name:"
                Label:
                    size_hint_y : None
                    height: 30
                    id: fs_name_inp

```

And the assignment in the root constructor is:

```
class FlightSummaryScreen(Screen):

    def __init__(self, flight,**kwargs):
        super(FlightSummaryScreen, self).__init__(**kwargs)

        breakpoint()
        self.ids.fs_name_inp.text = str("TestFlight"),


```
