### ISSUE TITLE
FileChooser: specifying `path` in FileChooserListView returns selected files with `path` included twice

### ISSUE THREAD

**Issue by liquiddandruff** [kivy/kivy#6571]
### Versions

* Python: 3.6
* OS: Windows 10, Linux
* Kivy: v1.11.1
* Kivy installation method: pip

### Description

There seems to be a problem with FileChooser when loading files from a specific directory:

Expected: correct path to selected file(s)

Actual: wrong path returned due to double inclusion of directory

Example: if `path: './schedules'` is in the kivy layout file, when `root.load(filechooser.path, filechooser.selection)` is called, the following is returned:

```
'C:\\Users\\steven\\projects\\gcs\\schedules\\schedules\\state1.pkl'
```

Instead of expected:

```
'C:\\Users\\steven\\projects\\gcs\\schedules\\state1.pkl'
```

A workaround like below was needed to get the right path:

### Code and Logs

Using example code: https://kivy.org/doc/stable/api-kivy.uix.filechooser.html

python:
```
class Root(FloatLayout):
    def load(self, path, filename):
        with open(os.path.join(path, filename[0])) as stream:
            self.text_input.text = stream.read()
        #       path='./schedules'
        #       filename=['C:\\Users\\steven\\projects\\gcs\\schedules\\schedules\\state1.pkl']
        fname_path = pathlib.PurePath(path) / pathlib.PurePath(filename[0]).name
        self.dismiss_popup()
```
kivy:
```
<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser
            path: './schedules'

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)
```
