### ISSUE TITLE
inspector overflow 

### ISSUE THREAD

**Issue by ronyeh3** [kivy/kivy#6598]
### Versions

* Python:2.7
* OS:ubuntu 18.04
* Kivy:1.11.1
* Kivy installation method: pip 

### Description

while inspect a widget, inspector can see properties from his sibling widgets and other instances of same widgets , and app **crashed** when click on property that not actually belong to this widget .
### Code and Logs

```python
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.bubble import Bubble
from kivy.uix.label import Label
from kivy.app import App
from kivy.uix.behaviors import DragBehavior
from kivy.lang import Builder

# You could also put the following in your kv file...
kv = '''

BoxLayout:
    RelativeLayout:
        ttt1:"dsad"
    RelativeLayout:
        ttt2:"452345"   #inspector can see ttt1 while inspecting me
'''

class TestApp(App):
    def build(self):
        return Builder.load_string(kv)

TestApp().run()
```

**Comment by gottadiveintopython** [comment]
Kivy-property probably is implemented by "descripter" which belong to a class not an instance.

**Comment by gottadiveintopython** [comment]
To avoid this issue, we should disallow to create new properties in instance rules in kv, which might break existing code.

```yaml
<MyWidget>:
    new_property: 'AAA'  # This is fine because this is in a class rule

MyWidget:
    new_property: 'AAA'  # This should be disallowed because this is in an instance rule
```

**Comment by ElliotGarbus** [comment]
The second case is not creating a property, it is assigning a value to the property.  
```
<MyWidget>:
    new_property: 'AAA'  # This creates a property and assigns a value.

MyWidget:
    new_property: 'AAA'  # This assigns a value to a property
```
FWIW: I prefer to create properties in python.

I suggest you close this issue.  If you would like to explore these ideas more, please use a support channel.  https://groups.google.com/g/kivy-users or the Kivy Discord Channel.
