### ISSUE TITLE
Win + v not working: Windows clipboard history

### ISSUE THREAD

**Issue by gregordr** [kivy/kivy#6644]
### Versions

* Python: 3.7
* OS: Windows 10
* Kivy: Latest
* Kivy installation method: pip

### Description

```
<UI>:
title: 'InputDialog'
auto_dismiss: False

RelativeLayout:
    orientation: 'vertical'
    pos: self.pos
    size: root.size

    TextInput:
        id: input
        hint_text:'test'
        pos_hint: {'center_x': 0.5, 'center_y': 0.725}
        size_hint: 0.95, 0.5

```

I have this UI in Kivy. Everything works as expected, however if I press win + v to open the windows clipboard history and try to paste in anything, kivy ignores it. Moreoever, the 'meta' key modifier will be stuck for the next few seconds, which will cause other shortcuts like ctrl + a or ctrl + v not to work.
