### ISSUE TITLE
ScrollView does not have an option for enabling overscroll effects when content fits in the viewport. It should.

### ISSUE THREAD

**Issue by elver** [kivy/kivy#6665]
How can I enable overscroll in scrollview for cases where the list is shorter than the viewport? Right now overscroll effects (and therefore overscroll-based refreshing as is common on touch interfaces) work great when the list does not fit on the screen, but when it does, there is no visual overscroll.

This problem can be seen most easily with this example: https://github.com/HeaTTheatR/KivyMD/wiki/Components-Refresh-Layout

Just limit the number of lines to about 5 so they can fit on the screen at once:

```python
    def set_list(self):
        names_icons_list = list(md_icons.keys())[self.x : self.y]
        for name_icon in names_icons_list[:5]:
            self.root.ids.box.add_widget(ItemForList(icon=name_icon, text=name_icon))
```

When creating the scrollview content by hand, there's a workaround as provided on discord by tshirtman:

```
ScrollView:
    id: scrollview
    BoxLayout:
        orientation: 'vertical'
        size_hint_y: None,
        height: self.minimum_height
        BoxLayout:
            id: content
            size_hint_y: None
            height: self.minimum_height
                # your current content
        Widget:
            size_hint_y: None
            height: max(0, scrollview.height - content.height + 1)
```

But in my case I'm using a RecycleView-derived class, so things get a lot more complicated and the fix is not as trivial.

* Python: 3.8
* OS: Linux Mint
* Kivy: dev
* Kivy installation method: pip install git+https://github.com/kivy/kivy.git@master
