### ISSUE TITLE
the size of the recycleview in kivy

### ISSUE THREAD

**Issue by hussam132** [kivy/kivy#6737]
I just found some code for  recycleview write in kv file and it's work fine but I have some question about some lines 

the kv file 

```
RecycleView:
    viewclass: 'Button'
    data: [{"text": "1"},{"text": "2"},{"text": "3"},{"text": "4"},{"text": "5"},{"text": "6"},{"text": "7"},{"text": "8"},{"text": "9"},{"text": "10"}]
    scroll_y: 1
    RecycleBoxLayout:
        id: layout
        default_size: None, None
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'
```

so I want to knew the use of this lines

```
default_size: None, None
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
```

so any one knew some explanation please tell me because it's horrible felling when you code work but you don't understand it
