### ISSUE TITLE
Memory Access Error with AsyncImage & RecyclerView

### ISSUE THREAD

**Issue by eman1can** [kivy/kivy#6829]
**Software Versions**
* Python: v3.8.1
* Kivy: 2.0.0dev0
* Kivy installation method: Github clone

**Loader Settings:**
* max upload per frame = 3
* num workers = 8

**Describe the bug**

Kivy exits with exit code -1073741819 (0xC0000005) when scrolling in a RecyleView of AsyncImages too quickly. I can't provide any code, but my layout looks like:
```
RecycleView:
    RecycleGridLayout:
        Widget: (~200 of these)
            AsyncImage
```

I believe the error to be caused when:
1. Widget enters viewport and recycleview creates it
2. AsyncImage start to load image from disk
3. Widget leaves viewport and recycleview deletes it
4. AsyncImage returns from loading Image from disk
5. Widget no longer exists and throws memory error
