### ISSUE TITLE
Allow using kv ids in RecycleView data keys

### ISSUE THREAD

**Issue by chavarinbonbyn** [kivy/kivy#6878]
**Software Versions**
* Python: 3.6.9 
* OS: Ubuntu 18.04.4 LTS
* Kivy: 1.11.0
* Kivy installation method: PIP

**Describe the bug**
The official information regarding recycleview shows the following: 
```yaml
<RV>:
    viewclass: 'Label' ### Here
    RecycleBoxLayout:
        default_size: None, dp(56)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'
```

Where viewclass is a simple Label widget with the attribute "text".  Created Label widgets within RV are populated as follows:

```python
class RV(RecycleView):
    def __init__(self, **kwargs):
        super(RV, self).__init__(**kwargs)
        self.data = [{'text': str(x)} for x in range(100)] ###### here one can see the class attribute 'text'
```

If one creates a more complicated widget for the viewclass within RecycleView as follows: 

```yaml
<MyRecycleView>:
    viewclass: 'ThisInfo' ### Mix of widgets
    RecycleBoxLayout:
        orientation: 'vertical'
        default_size: None, dp(120)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        spacing: 3

<ThisInfo@BoxLayout>:
    BoxLayout:
        size_hint_x: 1.3
        orientation: 'vertical'
        Label:
            id: name                 ### I should be able to modify this 'text' attribute from self.data by its id
        GridLayout:
            cols: 2
            Label:
                text: 'Position'
            Label:
                text: 'Salary'
            Label:
                id: position         ## Same here
            Label:
                id: salary           ### And here
```

And tries to populate in any of this ways, it does not populate any info, all the id fields appear blank.

```python
############### Method 1, placing the ID and attribute of the pertinent widget ###############
class MyRecycleView(RecycleView):
    def __init__(self,  **kwargs):
        super(MyRecycleView, self).__init__(**kwargs)

        self.data = [{'name.text': employee.name, 
                            'position.text': employee.position, 
                            'salary.text': employee.salary} 
                                 for employee in all_employees] 

######## Method 2, placing Id as the key of the widget and a dictionary for all of its attributes #####
class MyRecycleView(RecycleView):
    def __init__(self,  **kwargs):
        super(MyRecycleView, self).__init__(**kwargs)

        self.data = [{'name': {'text': employee.name}, 
                           'position': {'text': employee.position},
                           'salary': {'text':  employee.salary}} 
                               for employee in all_employees]
```

**Expected behavior**
The behavior is not consistent, when using a base class as Label, one may populate its attributes directly in the self.data list with 'text'. When using a mixture of widgets with separate ids one should be able to populate its attributes by its ID just as in all the rest of the kivy framework.

**Comment by tshirtman** [comment]
that's interesting, my way of achieving this is to simply map the properties of the internal widgets to properties on the root widget, and populate them there.

```yaml
<ThisInfo@BoxLayout>:
    name_text: ""
    salary_text: ""
    position_text: ""
    BoxLayout:
        size_hint_x: 1.3
        orientation: 'vertical'
        Label:
            text: root.name_text or ""
        GridLayout:
            cols: 2
            Label:
                text: 'Position'
            Label:
                text: 'Salary'
            Label:
                text: root.position_text or ""
            Label:
                text: root.salary_text or ""
```

and in python
```python
        self.data = [{'name_text': employee.name, 
                           'position_text': employee.position,
                           'salary_text':  employee.salary} 
                               for employee in all_employees]
``

Feel free to propose a pull request if you want your proposed way to work, but as you can't see the current way allow filling the need pretty easily, while (imho) defining the interface of the widget more clearly.
