### ISSUE TITLE
RecycleView self.rv.data.insert acts randomly

### ISSUE THREAD

**Issue by BananaMasterz** [kivy/kivy#6894]
**Software Versions**
* Python: 3.7
* OS: windows 10
* Kivy: 1.11.1
* Kivy installation method: anaconda

**Describe the bug**
I've been having a really hard time inserting a dictionary of more than one value in my recycle view data and that's the simplest way to recreate my issue: In the following code click "populate list" and then put whatever input you want in the "Insert new item" input box and click the button. You'll see that the new item was created but it affected other items as well. If you scroll the list you'll see more. 
```
from random import sample
from string import ascii_lowercase

from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout


kv = """
<Row@BoxLayout>:
    canvas.before:
        Color:
            rgba: 0.5, 0.5, 0.5, 1
        Rectangle:
            size: self.size
            pos: self.pos
    value: ''
    value2: ''
    Label:
        text: root.value
	Label:
		text: root.value2

<Test>:
    canvas:
        Color:
            rgba: 0.3, 0.3, 0.3, 1
        Rectangle:
            size: self.size
            pos: self.pos
    rv: rv
    orientation: 'vertical'
    GridLayout:
        cols: 3
        rows: 2
        size_hint_y: None
        height: dp(108)
        padding: dp(8)
        spacing: dp(16)
        Button:
            text: 'Populate list'
            on_press: root.populate()
        Button:
            text: 'Sort list'
            on_press: root.sort()
        Button:
            text: 'Clear list'
            on_press: root.clear()
        BoxLayout:
            spacing: dp(8)
            Button:
                text: 'Insert new item'
                on_press: root.insert(new_item_input.text)
            TextInput:
                id: new_item_input
                size_hint_x: 0.6
                hint_text: 'value'
                padding: dp(10), dp(10), 0, 0
        BoxLayout:
            spacing: dp(8)
            Button:
                text: 'Update first item'
                on_press: root.update(update_item_input.text)
            TextInput:
                id: update_item_input
                size_hint_x: 0.6
                hint_text: 'new value'
                padding: dp(10), dp(10), 0, 0
        Button:
            text: 'Remove first item'
            on_press: root.remove()

    RecycleView:
        id: rv
        scroll_type: ['bars', 'content']
        scroll_wheel_distance: dp(114)
        bar_width: dp(10)
        viewclass: 'Row'
        RecycleBoxLayout:
            default_size: None, dp(56)
            default_size_hint: 1, None
            size_hint_y: None
            height: self.minimum_height
            orientation: 'vertical'
            spacing: dp(2)
"""

Builder.load_string(kv)


class Test(BoxLayout):

    def populate(self):
        self.rv.data = [{'value': ''.join(sample(ascii_lowercase, 6))}
                        for x in range(50)]

    def sort(self):
        self.rv.data = sorted(self.rv.data, key=lambda x: x['value'])

    def clear(self):
        self.rv.data = []

    def insert(self, value):
        self.rv.data.insert(0, {'value': value, 'value2':value or 'default value'})

    def update(self, value):
        if self.rv.data:
            self.rv.data[0]['value'] = value or 'default new value'
            self.rv.refresh_from_data()

    def remove(self):
        if self.rv.data:
            self.rv.data.pop(0)


class TestApp(App):
    def build(self):
        return Test()


if __name__ == '__main__':
    TestApp().run()

```

**Expected behavior**
I was expecting only one item to be added at the top of the list with 2 same values as inputed. One on the left, and one on the right. I got that correctly, but it messed up other items randomly.
**To Reproduce**
Run the above code with the instructions and keep in mind, this code is from kivy's official examples. I just added
```
        value2: ''
	Label:
		text: root.value2
```
and modified the insert section to look like this:
```
    def insert(self, value):
        self.rv.data.insert(0, {'value': value, 'value2':value or 'default value'})

```
**Code and Logs and screenshots**
![image](https://user-images.githubusercontent.com/45745548/82765463-e4526000-9e1f-11ea-9b69-bb9a6bf871e3.png)

**Additional context**
As one can see, that "jmxwhi" should be empty on the right as the other items, instead it has "what is this" next to it which is the newly inserted item. Even if I clear the list and populate it again, I get random values with "what is this" next to them.
