### ISSUE TITLE
White Background during SlideTransition

### ISSUE THREAD

**Issue by todestoast** [kivy/kivy#6935]
**The Problem**
![output](https://user-images.githubusercontent.com/2900578/84451754-3aaf0380-ac54-11ea-9e24-4b9189fd38b3.gif)

As seen above during the transitions the background suddenly becomes white.

**What have I tried?**
- set background color for both Screens
- set clearcolor for ScreenManager
- set Background Color for ScreenManager
- also tested with native kivy elements (no KivyMD) - this has no effect

**My Code**
md.kv:
``` yaml
#:import C kivy.utils.get_color_from_hex
#: import ScreenManager kivy.uix.screenmanager.ScreenManager
<MainWindow>:
    name: "main"
    canvas:
        Color:
            rgba: C('#18294a')
        Rectangle:
            pos: self.pos
            size: self.size

    FloatLayout:
        Label:
            text:"Connect to this computer"
            font_size: 20
            color: C('#ffffff')
            pos_hint: {"x":.08, "y":.3}
            size_hint: 0.35, 0.15

        Label:
            text:"Connect to another computer"
            font_size: 20
            color: C('#ffffff')
            pos_hint: {"x":.58, "y":.3}
            size_hint: 0.35, 0.15

       MDIconButton:
            ripple_scale: 0
            #md_bg_color: app.theme_cls.primary_color
            theme_text_color: "Custom"
            text_color: C('#ffffff') 
            icon: "arrow-down-bold"
            user_font_size:"200sp"
            #md_bg_color: C('#ffffff') 
            pos_hint:{"x":0.1,"y":0.4}
            size_hint: .3, .3
            on_release:
                root.manager.transition.direction = "down"
                root.connectTo()

                
        MDIconButton:
            ripple_scale: 0
            #md_bg_color: app.theme_cls.primary_color
            theme_text_color: "Custom"
            text_color: C('#ffffff') 
            icon: "arrow-up-bold"
            user_font_size:"200sp"
            #md_bg_color: C('#ffffff') 
            pos_hint:{"x":0.6,"y":0.4}
            size_hint: .3, .3
            on_release:
                root.manager.transition.direction = "up"
                root.connectTo()

<ConnectToWindow>:
    name: "connectTo"
    canvas:
        Color:
            rgba: C('#18294a')
        Rectangle:
            pos: self.pos
            size: self.size

ScreenManager:
    clearcolor: C('#18294a')
    canvas:
        Color:
            rgba: C('#18294a')
        Rectangle:
            size: self.size
            pos: self.pos
    id: sm

```
main.py:
``` python
sm = ScreenManager(transition=SlideTransition())

class MainWindow(Screen):
    def connectTo(self):
        sm.current = "connectTo"


    def establishConnect(self):
        sm.current = "main"

class MyMainApp(MDApp):
    def build(self):
        kv = Builder.load_file("md.kv")
        screens = [MainWindow(name="main"),ConnectToWindow(name="connectTo")]
        for screen in screens:
            sm.add_widget(screen)

        sm.current = "main"
        return sm



if __name__ == "__main__":
    MyMainApp().run()
```
