### ISSUE TITLE
Slider gets incorrect value with step>0 and min!=0

### ISSUE THREAD

**Issue by Titousensei** [kivy/kivy#694]
A slider defined in a kv file with a step>0 and min!=0 will not slide within the correct interval. Example:

```
Slider:
    value: 15
    range: (10,90)
    step: 5
```

will slide between 0 and 80, and the cursor wil go out of the window for the values 0 an 5.

Tested on Linux debian amd64.
