### ISSUE TITLE
Can't change focus inside app running under Wayland

### ISSUE THREAD

**Issue by aneroid13** [kivy/kivy#7041]
**Software Versions**
* Python: v3.8.3 (default, May 17 2020, 18:15:42)
* OS: Manjaro Linux
* Kivy: v2.0.0rc3, git-20c14b2, 20200615
* Kivy installation method: pip install

**Describe the bug**
Focus can't be changed from one application UI element to another.

**Expected behavior**
User can focus on any UI element.

**To Reproduce**
Run kivy app under Wayland.

**Code and Logs and screenshots**

**w_test.py**
```python
from kivy.app import App

class w_testApp(App):
    title = "Wayland test"

    def __init__(self):
        super().__init__()

if __name__ == "__main__":
    w_testApp().run()
```
**w_test.kv**
```
GridLayout:
    cols: 1
    TextInput:
        id: one
        size_hint_y: None
        multiline: False
        height: 32

    TextInput:
        id: two
        size_hint_y: None
        multiline: False
        height: 32
        focus: True
```
![Wayland_test](https://user-images.githubusercontent.com/44608928/89809289-8ce1a780-db65-11ea-8970-fc2381319042.png)

**Example App:**
Only TextInput _id:two_ will be active. 
You can't change focus on TextInput _id:one_

**Additional context**
I developing my application on Manjaro Linux. 
I used KDE plasma that run under Xorg and everything was fine. 
But I lost ability to change focus between elements in my app when switch my system on plasma wayland mode.
