### ISSUE TITLE
BoxLayout pos_hint center calculation is wrong with padding

### ISSUE THREAD

**Issue by Titousensei** [kivy/kivy#706]
The positioning calculation seems to ignore padding, but the actual drawing is done with padding.

How to reproduce:

```
BoxLayout:
    orientation: 'vertical'
    padding: 100
    Button:
        text: 'full width, top'
    Button:
        pos_hint: {'center_x': 0.5}
        size_hint_x: 0.5
        text: 'should be x-centered'
    Button:
        text: 'full width, bottom'
```

I know contributing is not done like this, but here is the tiny patch:

```
diff --git a/kivy/uix/boxlayout.py b/kivy/uix/boxlayout.py
index b650a45..33b95a3 100644
--- a/kivy/uix/boxlayout.py
+++ b/kivy/uix/boxlayout.py
@@ -154,7 +154,7 @@ class BoxLayout(Layout):
                     elif key == 'top':
                         cy = y + selfh - value * h
                     elif key == 'center_y':
-                        cy = y + selfh / 2. - (value * h)
+                        cy = y + selfh / 2. - (value * h) - padding
                 c.x = cx
                 c.y = cy
                 c.width = w
@@ -183,7 +183,7 @@ class BoxLayout(Layout):
                     elif key == 'right':
                         cx = x + selfw - value * w
                     elif key == 'center_x':
-                        cx = x + selfw / 2. - (value * w)
+                        cx = x + selfw / 2. - (value * w) - padding

                 c.x = cx
                 c.y = cy
```
