### ISSUE TITLE
Unable to access kivy list outside the class 

### ISSUE THREAD

**Issue by npatted** [kivy/kivy#7168]
### main_file.py
```
import kivy

from kivy.app import App
from kivy.uix.boxlayout import 

from kivy.lang import Builder
from kivy.properties import ListProperty
import os
import csv

Builder.load_file('design2.kv')
data=[]

class MyWidget(BoxLayout):
    def open(self, path, filename):
        with open(os.path.join(path, filename[0])) as f:
            csv_data = csv.reader(f)
            datalines = list(csv_data)
            data.append(datalines)

class MyApp(App):
    def build(self):
        return MyWidget()


if __name__ == '__main__':
    MyApp().run()

```
### design2.kv
```
<MyWidget>:
    id: my_widget
    FileChooserListView:
        id: filechooser
        filters: ['*.csv']
        on_selection: my_widget.open(filechooser.path, filechooser.selection)

```
**I want to print datalines list in subfile ,and its printing empty list**
### subfile.py
```
from main_file import *
print(data)
```
