### ISSUE TITLE
Accordion custom initialization doesn't paint the 1st item

### ISSUE THREAD

**Issue by Titousensei** [kivy/kivy#725]
Initializing the collapse value of the AccordionItems will paint the first titlebar of the item only if the un-collapsed item is the first. If an item other than the first one is set to collapse=false, the first item will not be painted. (However, it is clickable). Same with setting the collapse value with code.

```
Accordion:
    orientation: 'vertical'

    AccordionItem:
        title: "a1"
        collapse: True
        Label:
            text: "A1"

    AccordionItem:
        title: "a2"
        collapse: True
        Label:
            text: "A2"

    AccordionItem:
        title: "a3"
        collapse: False
        Label:
            text: "A3"
```

Note: I'm assuming this is the right way to act on AccordionItems programmatically. If an other method should be used, please let me know.
