### ISSUE TITLE
ScrollView bug

### ISSUE THREAD

**Issue by Neizvestnyj** [kivy/kivy#7343]
* Python: 3.7, 3.8
* OS: Windows/Linux
* Kivy: 2.0.0
* Kivy installation method: pip

When the screen is flipped (in android and opening full screen on pc), the ScrollView with `effect_cls: "ScrollEffect"` does not scroll to the top. If you set `do_scroll_y = 1` when the window is resized, then after the flip the widgets will go up, but when you swipe from top to bottom, they will go off the screen (in android devices).

```
from kivy.app import App
from kivy.lang import Builder

kv = '''
BoxLayout:
    orientation: 'vertical'
    ScrollView:
        size_hint: (1, 1)
        effect_cls: "ScrollEffect"
        id: scroll
        BoxLayout:
            id: box
            orientation: 'vertical'
            size_hint_y: None
            height: self.minimum_height
            Button:
                text: 'Widget #1' 
                size_hint: 1, None
                height: 100
            Button:
                text: 'Widget #2' 
                size_hint: 1, None
                height: 100
            Button:
                text: 'Widget #3' 
                size_hint: 1, None
                height: 100
            Button:
                text: 'Widget #4' 
                size_hint: 1, None
                height: 100
            Button:
                text: 'Widget #5' 
                size_hint: 1, None
                height: 100
            Button:
                text: 'Widget #6' 
                size_hint: 1, None
                height: 100
'''


class TestApp(App):
    def build(self):
        return Builder.load_string(kv)


TestApp().run()
```

https://user-images.githubusercontent.com/40869738/105623826-edbc1e00-5e2d-11eb-9851-6c3fce2374cd.MP4
