### ISSUE TITLE
Parser exception on double indent

### ISSUE THREAD

**Issue by sanderland** [kivy/kivy#7345]
Kivy 2.0.0

An accidental double indent causes a rather nasty exception in the parser.

Example
```
    GridLayout:
        cols: 3
        rows: 2
        size_hint: 1, 5
        spacing: CP_SPACING
        DescriptionLabel:
            size_hint: 0.2, 1
            text: i18n._("contribute:savesgf")
        AnchorLayout:
            size_hint: 0.5, 1
            LabelledCheckBox:
                input_property: "contribute/savesgf"
        SmallDescriptionLabel:
            text: i18n._("contribute:savesgf:hint")
        DescriptionLabel:
            size_hint: 0.2, 1
            text: i18n._("contribute:movespeed")
        AnchorLayout:
            size_hint: 0.5, 1
            LabelledFloatInput:
                input_property: "contribute/movespeed"
        SmallDescriptionLabel:
                text: i18n._("contribute:movespeed:hint")  # causes the error
```
Error:
```
   ...
   File "...\kivy\lang\parser.py", line 674, in parse_level
     if current_property[:3] == 'on_':
 TypeError: 'NoneType' object is not subscriptable
```

Will look into the parser code later.
