### ISSUE TITLE
problem to SHOW POPUP

### ISSUE THREAD

**Issue by glira** [kivy/kivy#751]
I'm trying to get the button "CLICK TO SHOW POPUP" show the popup Login, by clicking the button I get a screen with the contents "No title"

follow my files that I believe are sufficient below:
main.py

```
if __name__ in ('__main__'):
    from app.gui import GuiApp
    GuiApp().run()
```

app/gui.kv

```
#:import random random.random
#:import SlideTransition kivy.uix.screenmanager.SlideTransition
#:import SwapTransition kivy.uix.screenmanager.SwapTransition
#:import WipeTransition kivy.uix.screenmanager.WipeTransition
#:import FadeTransition kivy.uix.screenmanager.FadeTransition
<CustomScreen>:

    hue: random()
    canvas:
        Color:
            hsv: self.hue, .5, .3
        Rectangle:
            size: self.size

    Label:
        font_size: 42
        text: root.name

    Button:
        text: 'CLICK TO SHOW POPUP'
        size_hint: None, None
        pos_hint: {'right': 1}
        size: 150, 50
        on_release: root.login.open()

    Button:
        text: 'Previous screen'
        size_hint: None, None
        size: 150, 50
        on_release: root.manager.current = root.manager.previous()

    BoxLayout:
        size_hint: .5, None
        height: 250
        pos_hint: {'center_x': .5}
        orientation: 'vertical'

        Button:
            text: 'Use SlideTransition with "up" direction'
            on_release: root.manager.transition = SlideTransition(direction="up")

        Button:
            text: 'Use SlideTransition with "down" direction'
            on_release: root.manager.transition = SlideTransition(direction="down")

        Button:
            text: 'Use SlideTransition with "left" direction'
            on_release: root.manager.transition = SlideTransition(direction="left")

        Button:
            text: 'Use SlideTransition with "right" direction'
            on_release: root.manager.transition = SlideTransition(direction="right")

        Button:
            text: 'Use SwapTransition'
            on_release: root.manager.transition = SwapTransition()

        Button:
            text: 'Use WipeTransition'
            on_release: root.manager.transition = WipeTransition()

        Button:
            text: 'Use FadeTransition'
            on_release: root.manager.transition = FadeTransition()
<Login>:
    size_hint: .5, .5
    auto_dismiss: False
    title: 'Hello world'
    Button:
        text: 'Click me to dismiss'
        on_press: root.dismiss()

```

app/gui.py

```
from kivy.uix.popup import Popup
from kivy.uix.button import Button
from kivy.app import App
from kivy.uix.screenmanager import ScreenManager, Screen,ObjectProperty
from kivy.properties import NumericProperty


#enable debug
from kivy.config import Config
Config.set('modules', 'inspector', '')


class Login(Popup):
    pass

class CustomScreen(Screen):
    login = ObjectProperty(Login())
    hue = NumericProperty(0)


class GuiApp(App):

    def build(self):
        root = ScreenManager()
        for x in xrange(4):
            root.add_widget(CustomScreen(name='Screen %d' % x))
        #return root

        #b = Button()
        #b.bind(on_press=self.show_login)
        #root.add_widget(self.show_login())

        return root

    def show_login(self):
        p = Login()
        p.open()
```
