### ISSUE TITLE
ToggleButton doesn't look like it's "disabled" when created programatically

### ISSUE THREAD

**Issue by martinsik** [kivy/kivy#7526]
**Software Versions**
* Python: Python 3.8
* OS: Win 10
* Kivy: 2.0.0
* Kivy installation method: pip install kivy

**Describe the bug**

I posted this issue on Discord a few days ago without any response, so I'm posting it here as well because it looks like a bug to me.

When creating a disabled `ToggleButton` programatically the button has disabled state (it's not clickable) but it seems like `disabled_color` is not set on the label or something(?) so it looks like the button is still enabled.
However, when creating a disabled `ToggleButton` in a `kv` file (or disabling it later in code) it works as expected.

**Expected behavior**

Both buttons should look like they are disabled.

**To Reproduce**

```
# main.py
from kivy.app import App
from kivy.properties import ObjectProperty
from kivy.uix.togglebutton import ToggleButton
from kivy.uix.widget import Widget


class PongGame(Widget):
    target_layout = ObjectProperty(None)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.target_layout.add_widget(ToggleButton(
            disabled=True,  # button will be disabled but won't look like it's disabled
            size_hint=(None, None),
            text="My button",
            size=(300, 100),
        ))


class PongApp(App):
    def build(self):
        return PongGame()


if __name__ == '__main__':
    PongApp().run()
```
```
# pong.kv
<PongGame>:
    target_layout: layout

    StackLayout:
        id: layout
        size: self.parent.size
        canvas:
            Color:
                rgba: [1, 1, 0, 0.75]
            Rectangle:
                pos: 0, 0
                size: self.width, self.height

        ToggleButton:
            size_hint: None, None
            text: "My button"
            size: 300, 100
            disabled: True  # button is disabled
```

In this example, both buttons are disabled but the second button created in code doesn't look like it's disabled.

**Code and Logs and screenshots**

![kivy-toggle-button-disabled-test](https://user-images.githubusercontent.com/238765/117845981-4f8b8100-b281-11eb-91f4-a39d0563bd25.png)
