### ISSUE TITLE
AttributeError: 'super' object has no attribute '__getattr__' while trying access self.root.ids

### ISSUE THREAD

**Issue by comand100vip** [kivy/kivy#7607]
**Software Versions**
* Python: 3.9.6
* OS: Windows 8.1
* Kivy: v2.0.0
* Kivy installation method: PIP

**Describe the bug**
While trying to access `self.root.ids.user.text` and `self.root.ids.password.text` it raise error `AttributeError: 'super' object has no attribute '__getattr__`

**Expected behavior**
Then I click "Wyczyść" (clear) it tries to execute `clear` function but can't access `self.root.ids`.

**To Reproduce**
Copy code below (NOTE: I am using KivyMD but I had same issue that used just Kivy)

**Code and Logs and screenshots**

**main.py**
```python
from kivy.uix.screenmanager import ScreenManager, Screen
from kivy.lang import Builder
from kivymd.app import MDApp
import codecs  # Help read special characters that are in my lenguage like: ę, ą, ć, ś, ń, ż, ź


class MenuScreen(Screen):  # created class to handle Menu screen (aka login screen)
    pass


class MainScreen(Screen):  # main screen of application
    pass


class App(MDApp):
    def __init__(self, **kwargs):
        super(App, self).__init__(**kwargs)

    def build(self):
        with codecs.open("px.kv", "r", "utf-8") as f:  # read kivy file and as I mentioned above I use codecs to read some symbols
            gui_content = f.read()
        GUI = Builder.load_string(gui_content)
        self.theme_cls.theme_style = "Dark"
        self.theme_cls.primary_palette = "Gray"
        sm = ScreenManager()
        sm.add_widget(MenuScreen(name="menu"))
        sm.add_widget(MainScreen(name="main"))
        return sm

    def login(self):
        print("CALLED!")
        self.root.transition.direction = "left"
        self.root.current = "main"

    def logout(self):
        print("CALLED!")
        self.root.transition.direction = "right"
        self.root.current = "menu"

    def navigation_drawer(self):
        print("Navigation Drawer Open!")

    def clear(self):
        self.root.ids.user.text = ""  # here is problem assccesing ids
        self.root.ids.password.text = ""


if __name__ == '__main__':
    App().run()
```

**px.kv**
```
<MenuScreen>:
    Image:  # this image can be cut out or replaced with something else, but I don't want post here original image
        source: "./resources/VP_logo.png" 
        pos_hint: {"center_x": .5, "center_y": .8}
        size_hint: .6, .3

    MDTextFieldRound:
        id: user
        hint_text: "E-Mail"
        icon_left: "account"
        size_hint_x: 0.8
        font_size: 18
        pos_hint: {"center_x": 0.5, "center_y": 0.55}
        normal_color: .2, .2, .2, 1
        color_active: 1, 1, 1, 1
        required: True

    MDTextFieldRound:
        id: password
        hint_text: "Hasło"
        icon_left: "key-variant"
        size_hint_x: 0.8
        width: 200
        font_size: 18
        pos_hint: {"center_x": 0.5, "center_y": 0.43}
        password: True
        normal_color: .2, .2, .2, 1
        color_active: 1, 1, 1, 1
        required: True

    MDCheckbox:
        active: False
        size_hint: (None, None)
        pos_hint: {'center_x': .1, 'center_y': .36}

    MDRoundFlatButton:
        text: "Zaloguj się"
        font_size: 12
        pos_hint: {"center_x": .2, "center_y": .25}
        on_press: app.login()

    MDRoundFlatButton:
        text: "Wyczyść"
        font_size: 12
        pos_hint: {"center_x": .8, "center_y": .25}
        on_press: app.clear()

<MainScreen>:
    BoxLayout:
        orientation: "vertical"
        MDToolbar:
            title: "PX - (Name of the user)"
            left_action_items: [["menu", lambda x: app.navigation_drawer()]]
            elevation: 10
        GridLayout:
            cols: 1
            # size_hint_y: 1
            # orientation: "vertical"
            # halign: "center"
            MDRoundFlatButton:
                text: "Go back to login"
                font_size: 12
                # pos_hint: {"center_x": 0.5, "center_y": 0.5}
                pos_hint_x: 0.5
                on_press: app.logout()
```

How it looks before rasing error;
![image](https://user-images.githubusercontent.com/82674108/131528901-836db620-620e-4b16-acda-6a498aa60da7.png)

**Additional context**
I arledy see some people having this problem, But I don't find anything working, so this is why I am asking here.
