### ISSUE TITLE
WIP - Line.round_rectangle corner processing issue.

### ISSUE THREAD

**Issue by podraco** [kivy/kivy#7656]
**Software Versions**
* Python: 3.9
* OS: Windows 10 (Not relevant)
* Kivy: dev
* Kivy installation method: source

## Description
when we provide the data for the line instruction to draw a rounded rectangle, the corners are miss processed, if the resolution is left below 8, we can see that the points processed doesn't correspond to the correct points the rounded rectangle should have, also the segments and the resolution parameter doesn't correspond to the definition in the documentation.

### Expected behavior
Process the corners with the amount of segments we parse by corner, rather than in general.
0 = no segments, a square
1 = 1 segment, on the corner
2+ = 2 or more segments per corner.

A segment is a rect., a line that connects 2 points on the corners, between the origin of the arc and the control point.
The control points are the ends of the arc, since the math formula skips to the next value.

**To Reproduce**
set a widget with a canvas instruction with the [x, y, width, height, *radius, resolution]

**Code and Logs and screenshots**
#### Images:
current processing:
![python_A4KwGKov1P](https://user-images.githubusercontent.com/5509325/136835970-aa3da8c7-f938-47d8-ac68-4624ac55a846.png)

expected processing path (without the control points):
![inkscape_Y6vrcMCebH](https://user-images.githubusercontent.com/5509325/136836001-e3500e27-e338-43f3-8e92-d235b19a19ee.png)

#### kivy code:
```yaml
<LineWidget>:
    canvas.before:
        Color:
            rgba: root.color
        RoundedRectangle:
            pos: root.pos
            size: root.size
            segments: root.segments
            radius: root.radius
        Color:
            rgba: root.line_color
        Line:
            width: root.line_width
            rounded_rectangle: (self.x, self.y, self.width, self.height, *root.radius, self.line_segments)

AnchorLayout:
                        anchor: "center", "center"
                        LineWidget:
                            id: button1
                            size: (160, 64)
                            size_hint: (None, None)
                            line_color: 1,0,0,1
                            color: 0,1,0,1
                            radius: 32
                            on_radius:
                                t1.text = f"radius = {button1.radius}"
                            on_line_segments:
                                t2.text = f"line_segments = {button1.line_segments}"
```
#### Python Code
```python
from kivy.uix.widget import Widget
from kivy.app import App
from kivy.properties import *

class LineWidget(Widget):
    color = ColorProperty()
    line_color = ColorProperty()
    segments = NumericProperty(0)
    line_segments = NumericProperty(0)
    line_width = NumericProperty(2)
    radius = VariableListProperty(0, length=4)

class app(App):

    def build(self, *dt):
        return Builder.load_string(kv)

app().run()
```

**Additional context**
this issue is not visible if resolution is higher than 16,32, in small widgets, but the bigger the arc, the more apparent it is.
