### ISSUE TITLE
Stencil cancelled on intersection of shapes

### ISSUE THREAD

**Issue by tdubourg** [kivy/kivy#790]
Hi,

When we use the StencilPush instructions, if we want to define the stencil as a complex shape like a  trianle and an ellipse together, on the intersection of the two shapes, the stencil will simply be cancelled.

Example : 

```
    StencilPush
    Color:
        rgba: 1, 0, 0, 1
    Rectangle:
        pos: 50,50
        size: 20, 20
    Ellipse:
        pos: 50, 55
        size: 15, 15
    ... then all the other stencil instructions...
```

Expected behaviour : a stencil of the shape of a square.

It actually happen no matter what type of shape we draw in the StencilPush : line, quad, etc. ... 

The is VERY problematic because it only allow us to use simple shapes or to compute intersection and draw complex shapes instead of simple ones to avoid intersection.

Especially if the stencil position if moving (like the sight of a player in the dark) and we have another shape somewhere on the canvas (let's say a spot light) then everything will work at the begining... and stop working properly when intersection of the two shapes will happen.
