### ISSUE TITLE
Images strangely distorted when scaled down.

### ISSUE THREAD

**Issue by Julian-O** [kivy/kivy#7944]
**Software Versions**
* Python: 3.11
* OS: Windows 11
* Kivy: 2.1.0
* Kivy installation method: pip install kivy

**Describe the bug**
I have buttons with `background_normal` images pointing to .png files.
I specify the height and width to be a moderately small fraction of the size of the original images (e.g. 100-150 px wide where the original is 1400-2000 px wide).

The images are shrunk to size, but have these weird stretched-out protuberances along the middle axes - the more they are shrunk, the more the issue.

e.g. Original image (a Chrome logo) as 2000x2000 png.
![logo_Chrome](https://user-images.githubusercontent.com/945973/183313701-60f6c61b-ef8d-4b73-b40a-12301e57d568.png)

It's appearance in Kivy (as one of 5 buttons) when shrunk to 100x100.

![image](https://user-images.githubusercontent.com/945973/183313728-8838eb9b-c8d3-4046-9cb5-9eb62c40e7b2.png)

**Expected behavior**
Image to be resized with loss of detail but without distortions.

**To Reproduce**

The .kv code is pretty straight forward for this example:

```
GridLayout:
    cols: 2
    width: 250
    padding: 30
    spacing: 30
    [... other buttons ...]
    Button:
        background_normal: 'resources/logo_Chrome.png'
        size_hint: None, None
        width: 100
        height: 100
        on_press:
            guiactions.trigger_app(app, "Chrome")
    [... other buttons ...]
```
