### ISSUE TITLE
Kivy, remove_widget

### ISSUE THREAD

**Issue by Denchik937** [kivy/kivy#8036]
**2.1.0**
* Python: 3.10
Please, how to delete a widget from another class???
when I click on the Click del button in another window, the Label Hello World widget should be deleted

.py
```
from kivy.app import App
from kivy.uix.screenmanager import ScreenManager, Screen
from kivy.core.window import Window


Window.size = (375, 565)

class Test_1(Screen):
    def dell(self):
        a = self.manager.get_screen('test2').ids.gg_1.remove_widget(self.ids.gg)
        print(a)

class Test_2(Screen):
    pass

class Test(App):
    def build(self):
        sm = ScreenManager()

        sm.add_widget(Test_1(name='test1'))
        sm.add_widget(Test_2(name='test2'))

        return sm

if __name__ == '__main__':
     

> `Test().run()`
```

.kv
```
<Test_2>:
    BoxLayout:
        id: gg_1
        orientation: 'vertical'
        Label:
            id: gg
            text: 'Hellow World'
        Button:
            text: ' Back'
            on_press: root.manager.current = 'test1'

<Test_1>:
    BoxLayout:
        orientation: 'vertical'
        Button:
            text: 'Click del'
            on_press: root.dell()
        Button:
            text: 'Click next'
            on_press: root.manager.current = 'test2'
```
