### ISSUE TITLE
Resize checkbox

### ISSUE THREAD

**Issue by DoubtBrep** [kivy/kivy#8052]
I think what I want is simple, but I don't see any way of doing it.

I want to be able to set the size of the checkbox. I have a label next to one that resizes, but the checkbox stays the same size.

If this can already be done please educate me and I will share the informational wealth.

Thank you team.

Here's an example of what I'm using.

```
CheckBox:
		id: remember
		active: False
		size_hint_y: None
		size_hint_x: 1
		height: '36dp'
		width: '30dp'
		pos_hint: {'left':1.0, 'top':0.045}
```

**Comment by kuzeyron** [comment]
This is a support question and not a issue. For future support question please visit us on Discord!
Your code could look like this:
```
CheckBox:
	id: remember
	active: False
	size_hint_y: None
	size_hint_x: 1
	height: '36dp'
	width: '30dp'
	pos_hint: {'left':1.0, 'top':0.045}
	canvas:
		Clear
                Color:
                      rgba: self.color
                Rectangle:
                     source: self._radio_image if self.group else self._checkbox_image
                     size: sp(32), sp(32)
                     os: int(self.center_x - sp(16)), int(self.center_y - sp(16)
```
