### ISSUE TITLE
TextInput crashes while pressing letter 'w' with specified font_size

### ISSUE THREAD

**Issue by Marcinosoft** [kivy/kivy#8108]
**Software Versions**
* Python: 3.8.10
* OS: Windows 10 (22H2) and Windows 11 (22H2)
* Kivy: 2.1.0
* Kivy installation method: pip install --upgrade kivy[full] kivy_examples

**Describe the bug**
When TextInput font_size is set to 150 or 160 app crashes when user is trying to enter letter 'w'. It does not happen when font_size is for example set to 140, 170 or 180.

App crashes with console output:
`Process finished with exit code -1073741784 (0xC0000028)`

**To Reproduce**
main.py

```
from kivy.app import App

class TestApp(App):
    pass

TestApp().run()
```
test.kv
```
BoxLayout:
    orientation: 'vertical'
    size: root.width, root.height
    Label:
        text: 'Try to input letter w in TextInput below'
    TextInput:
        font_size: 150
```
