### ISSUE TITLE
problem with collision (simulating gravity)

### ISSUE THREAD

**Issue by boris342** [kivy/kivy#8128]
I have a simple code where the ball bounces off the paddle and what i would like to achieve is make ball grounded after the bouncing of the ball ends. So i would like to simulate gravity. Problem is that collide_widget does not detect collision properly. I expect collide_widget will detect collision when ball.y == paddle.top but it detect collision when ball.y < paddle.top and it is always different depending on starting position of ball.

gravity.py

```

import kivy
kivy.require('1.11.1')

from kivy.app import App
from kivy.uix.widget import Widget
from kivy.properties import NumericProperty, ReferenceListProperty
from kivy.vector import Vector
from kivy.clock import Clock

DELTA_TIME = 1.0 / 60.0

class Ball(Widget):
    velocity_x = NumericProperty(0)
    velocity_y = NumericProperty(0)
    velocity = ReferenceListProperty(velocity_x, velocity_y)

    def move(self, dt):
        self.pos = Vector(*self.velocity) *dt + self.pos

class Paddle(Widget):
    velocity_x = NumericProperty(0)
    velocity_y = NumericProperty(0)
    velocity = ReferenceListProperty(velocity_x, velocity_y)

    def move(self, dt):
        self.pos = Vector(*self.velocity) *dt  + self.pos

class GravityBall(Ball):
    def update(self, dt, idle):
        if idle == 0:
            self.velocity_y -= 20
            self.move(dt)
        else: 
            self.velocity_y = 0
            self.move(dt)

class GravityGame(Widget):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.idle = 0
        self.ball = GravityBall()
        self.ball.center = (200,300)
        self.add_widget(self.ball)

        self.paddle = Paddle()
        self.paddle.center = (200,100)
        self.add_widget(self.paddle)

        Clock.schedule_interval(self.update, DELTA_TIME)

    def update(self, dt): 

        self.ball.update(dt, self.idle) 
        self.paddle.move(dt) 
        
        if self.ball.collide_widget(self.paddle) and self.ball.y+5 >= self.paddle.top:
            self.ball.velocity_y *= -1
            self.idle = 0     
        elif self.ball.collide_widget(self.paddle) and self.ball.y+5 < self.paddle.top:
            self.idle = 1


class GravityApp(App):
    def build(self):
        return GravityGame()

if __name__ == '__main__':
    GravityApp().run()

```
gravity.kv

```

#:kivy 1.11.1

<GravityBall>:
    size: 30, 30
    canvas:
        Ellipse:
            pos: self.pos
            size: self.size

<Paddle>:
    size: 100, 30
    canvas:
        Color:
            rgb: 1, 0, 1
        Rectangle:
            pos: self.pos
            size: self.size


```
