### ISSUE TITLE
Throw exception for screens that do not have a name

### ISSUE THREAD

**Issue by benpayne** [kivy/kivy#8160]
I created a few screens under a screen manager in a kv file and forgot to specify the "name" property on all of them.  As a result I was not able to change to another screen once the program ran.  I suspect that it saw all screens with the same name of empty string and thought I was already on the screen I was asking for.  So it seems needed to create a unique name for each screen.  As such it would be ideal if an exception was thrown if a screen was created without a name.  Also it would be nice if a screen was added to a screen manager with a non-unique name that it also throw an exception.  

Example:

```
ScreenManager:
        id: top_screen_manager
        Screen:
            id: screen1
            _name: "screen1"_
            Label:
                text: 'This is screen 1'

        Screen:
            id: screen2
            _name: "screen2"_
            Label:
                text: 'This is screen 2'
```

Then in py file:

```
    self.ids.top_screen_manager.switch_to(self.ids.screen2)
```

If both names were omitted this switch_to function would not do anything.
