### ISSUE TITLE
Sinhala letters are not complete in some places in kivy Label and sinhala font in kivy TextInput is wrong

### ISSUE THREAD

**Issue by ghost** [kivy/kivy#8182]
The Sinhala font has been successfully rendered by Kivy, but in some places the letters in the Kivy Label are not 100% complete. **'යා'** is cut off in Kivy label. But the KivyMD label does not have this problem.

![Untitled](https://user-images.githubusercontent.com/107760735/226545966-2586bbbd-a017-4b73-bf82-267a921bf64e.png)

And this error appears in `TextInput`
Code example:
```
GridLayout:
    cols: 1
    padding: dp(10)
    spacing: dp(10)
    Label:
        text: "පාරිභෝගිකයා"
        font_size: sp(50)
        font_name: "NotoSansSinhala"
        font_script_name: "Sinh"
        font_direction: "ltr"

    TextInput:
        text: "පාරිභෝගිකයා"
        font_size: sp(50)
        font_name: "NotoSansSinhala"
        font_script_name: "Sinh"
        font_direction: "ltr"
```
As long as the `Label` is there, Sinhala font is displayed successfully in the `TextInput`. But when the `Label` is removed, Sinhala font is displayed incorrectly in the `TextInput`.

![Screenshot 2023-03-21 155541](https://user-images.githubusercontent.com/107760735/226579311-b7f610d8-1c35-4df3-9418-f3bbedf37f86.png)

https://user-images.githubusercontent.com/107760735/226547901-21f98044-9fcb-4470-a925-80350819432d.mp4

And the `font_size` of the `Label` should be the same as the `TextInput`. If the `font_size `of the `Label `and the `font_size `of the `TextInput` are unequal. Sinhala characters are displayed incorrectly only in `TextInput`.

**It is essential to successfully display the Sinhala language in our applications. Please help.**

_Originally posted by @31mpmp in https://github.com/kivy/kivy/issues/8148#issuecomment-1477422726_
