### ISSUE TITLE
Incorrect display of Sinhala language in Kivy TextInput

### ISSUE THREAD

**Issue by 31mpmp** [kivy/kivy#8224]
**Software Versions**
* Python: 3.10.9
* OS: Windows, Android
* Kivy: master
* Kivy installation method: pip install kivy

I rendered the following text with google Noto Sans Sinhala in kivy `TextInput` and it rendered incorrectly. As we want to support Sinhala languages in our applications. Please help

Example  code:
```
TextInput:
        text: "පාරිභෝගිකයා  "
        font_name: "NotoSansSinhala.ttf"
        font_script_name: "Sinh"
        font_direction: "ltr"
```

Expected output:
### පාරිභෝගිකයා

Kivy application output:
![Screenshot 2023-03-21 155541](https://user-images.githubusercontent.com/107760735/226579311-b7f610d8-1c35-4df3-9418-f3bbedf37f86.png)
