### ISSUE TITLE
Enquiry: Why Kivy Button to respond to any or all clicks of the screen ??

### ISSUE THREAD

**Issue by CapeCrusader321** [kivy/kivy#8293]
Hey there probably wrong place to ask and also wrong format, sorry for that, but am beginning kivy, in my simple project consisting of a button,text-input and a label, the button is super-sensitive and responds to any clicks on the screen(I touch the input box or any side of the screen) the button executes its function, this makes my project not less than pathetic as the button just randomly executes without even being touched.
Here are some parts of my code relating to the button:

```
Button:
MyButton:
            text: "Submit"
            pos_hint: {'x':.4,'y':.28}
            size_hint: .2,.2
            on_press: root.press()
```

```
Function:
class AppScreen(Widget):

    link= ObjectProperty(None)

    def press(self):
        link= self.link.text
        print(link)
```
Can anyone help me with suggesting a way with which i could limit the button to respond only when its clicked and not respond to any click outside it body. I did google and checked forums but i couldn't get an appropriate answer, please do help.

**Comment by mak8kammerer** [comment]
From kivy's docs:
`on_touch_down(), on_touch_move(), on_touch_up() don’t do any sort of collisions. If you want to know if the touch is inside your widget, use collide_point().`
Look at this [function](https://kivy.org/doc/stable/api-kivy.uix.widget.html#kivy.uix.widget.Widget.collide_point).

**Comment by CapeCrusader321** [comment]
> From kivy's docs: `on_touch_down(), on_touch_move(), on_touch_up() don’t do any sort of collisions. If you want to know if the touch is inside your widget, use collide_point().` Look at this [function](https://kivy.org/doc/stable/api-kivy.uix.widget.html#kivy.uix.widget.Widget.collide_point).

So basically i will use collide point to determine at which coordinates of touch should the button react, i dont know the synatx but correct me if am wrong:

```
MyButton:
            text: "Submit"
            pos_hint: {'x':.4,'y':.28}
            size_hint: .2,.2
            collide_point: 100,200 
            on_press: root.press()
```

Is this correct ??
