### ISSUE TITLE
Disabling all Custom widget button already displayed, on selecting anyone of the button

### ISSUE THREAD

**Issue by santhoshakashs24** [kivy/kivy#8322]
**abc.kv**
```
<Option>
    size_hint_y: None
    pos_hint: {"x": .02}
    size: 50, 50
    user_font_size: "15sp"
    theme_text_xolor: "Custom"
    text_color: 1, 1, 1, 1
    on_release: app.optionSelect(self.id,self.type), root.disable_Button()
    canvas.before:
        Color:
            rgb: (1, 1, 1, 1)
        RoundedRectangle:
            size: self.width, self.height
            pos: self.pos
            radius: [23, 23, 23, 0]

MDScreen:
    add_list: add_list
    name: "list"
    MDFloatLayout:
    ....
    ScrollView:
    ....
```

**abc.py**

```
listContent = ['A','B','C','D',E']

class Option(MDFillRoundFlatButton):
    id = NumericProperty()
    text = StringProperty()
    type = StringProperty()

    def disable_Button(self):
        self.disabled = True
        
class ABC(MDApp):

        def applicationOption(self, *args):
            global listContent
            msg = "Select the value?"
            screen_manager.get_screen('list').add_list.add_widget(Response(text=msg, size_hint_x=ABC.contentSize(msg), 
            halign="center"))
          for i in range(len(listContent)):
              opt = Option(id=i,text=listContent[i],type="Test")
              screen_manager.get_screen('list').add_list.add_widget(opt)

        def optionSelect(self,id,type):
            if type == "Test":
                value = listContent[id]
                print(value)
        
        def build(self):
            screen_manager = ScreenManager()
            screen_manager.add_widget(Builder.load_file("abc.kv"))
            Clock.schedule_once(self.applicationOption, 4)
            return screen_manager

if __name__=="__main__":
    ABC().run()
```
    
    
In the above example, the listContent is displayed and when selecting anyone of the value from the custom widget(Option) the value is printed in the console and the button is disabled. But how do I disable the whole set of options(list content displayed by type) as I have multiple Options which displays based on type in the program.
