### ISSUE TITLE
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute. Remaining events:

### ISSUE THREAD

**Issue by EmptyMarbleJar** [kivy/kivy#8344]
I am experiencing this same issue, but I narrowed my error down to something with the Kivy Slider ".value" property. 

If I remove any code that explicitly states what you want the value to be.

Example. This code does not fire an error when used but the simple change below causes the error and only when re-sizing my screen.

```
<Slider_Property_Frame>
    id: sliderpropframe
    cols: 1
	size_hint: [1, None]
    adaptive_height: True
    padding: [0,5,0,5]
    line_width: 1
    line_color: 0,0,0,1

    MDLabel:
        id: propertylabel
        size_hint: [None, None]
        width: sliderpropframe.width
        height: 20
        text: "Property Text"
        halign: "center"

    MDGridLayout:
        cols: 1 
        size_hint: [1, None]
        padding: [0,0,0,0]
        height: 50

        MDLabel:
            size_hint: [1, None]
            height: 20
            text: f"Min: {int(minslider.value)}"
            halign: "center"

        MDGridLayout:
            id: minslidergrid
            size_hint: [1, None]
            height: 30
            padding: [5,5,5,5]
            cols: 3

             
            MDLabel:
                size_hint: [None, None]
                width: 30
                height: 20
                text: f"0"

            MDSlider:
                id: minslider
                size_hint: [None, None]
                width: minslidergrid.width-70
                height: 20
                disabled: (True if self.max==0 else False)
                step: 1
                show_off: True
                min: 0
                max: int(maxslider.value)

            MDLabel:
                size_hint: [None, None]
                width: 30
                height: 20
                text: f"{int(maxslider.value)}"

    MDGridLayout:
        cols: 1 
        size_hint: [1, None]
        padding: [0,0,0,0]
        height: 50

        MDLabel:
            size_hint: [1, None]
            height: 20
            text: f"Max: {int(maxslider.value)}"
            halign: "center"

        MDGridLayout:
            id: maxslidergrid
            size_hint: [1, None]
            height: 30
            padding: [5,5,5,5]
            cols: 3
             
            MDLabel:
                size_hint: [None, None]
                width: 30
                height: 20
                text: f"{int(minslider.value)}"

            MDSlider:
                id: maxslider
                size_hint: [None, None]
                width: maxslidergrid.width-70
                height: 20
                step: 1
                show_off: True
                min: int(minslider.value)
                max: 100

            MDLabel:
                size_hint: [None, None]
                width: 30
                height: 20
                text: "100"
```

Simple change that causes an error is simply adding the value to any slider: 

```
            MDSlider:
                id: minslider
                size_hint: [None, None]
                width: minslidergrid.width-70
                height: 20
                disabled: (True if self.max==0 else False)
                step: 1

                value: 50

                show_off: True
                min: 0
                max: int(maxslider.value)


            MDSlider:
                id: maxslider
                size_hint: [None, None]
                width: maxslidergrid.width-70
                height: 20
                step: 1

                value: 50

                show_off: True
                min: int(minslider.value)
                max: 100
```
Not sure why this simple change causes this dramatic error to appear.

_Originally posted by @EmptyMarbleJar in https://github.com/kivy/kivy/issues/7606#issuecomment-1669659302_
            
![Capture1](https://user-images.githubusercontent.com/92820844/259122410-969f42e5-eaa0-4cee-965f-b8c9aa2a23d5.PNG)

Alternatively using python to change the value instead of putting it directly into the kivy file spits the same error - 

```
class Slider_Property_Frame(MDGridLayout):
    value = NumericProperty()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        Clock.schedule_once(self.set_defaults)

    def set_defaults(self, interval):
        self.ids.maxslider.value = 50
```
