### ISSUE TITLE
Documentation of the load_kv() method of kivy.App is incorrect

### ISSUE THREAD

**Issue by DaytonaJohn** [kivy/kivy#8518]
**Software Versions**
* Python: Any
* OS: Any
* Kivy: 2.3.0.dev0
* Kivy installation method: Any

**Describe the bug**
The current documentation states:

> This method will search for a file named showcase.kv in the directory that contains main.py. The name of the kv file has to be the lowercase name of the class, without the ‘App’ postfix at the end if it exists.

This is incorrect, the name of the kv file is the lowercase name of the class, with or without the ‘App’ postfix. 

**Expected behavior**
I expect the documentation to be correct

**To Reproduce**
run the following code and note that the kv file is automatically loaded by the kivy.App code.
python file:

```
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout


class MyGameScreen(BoxLayout):

    def __init__(self):
        super(MyGameScreen, self).__init__()
        self.i = 0

    def btn_push_press(self):
        if self.i == 0:
            self.btn_push.back_color = (0, 0, 1, 1)
            self.btn_push.pressed_color = (1, 0, 0, 1)
            self.i = 1
        elif self.i == 1:
            self.btn_push.back_color = (0, 1, 1, 1)
            self.btn_push.pressed_color = (1, 0, 1, 1)
            self.i = 0

class MyCoolApp(App):
    def build(self):
        return MyGameScreen()


if __name__ == '__main__':
    MyCoolApp().run()
```

kv file named "mycoolapp.kv":

```
<MyGameScreen>:
    btn_push: btn_push

    BoxLayout:
        id: game_screen
        orientation: 'vertical'

        MyRoundedButton_push:
            id: btn_push
            text: "PUSH"
            font_size: 48
            color: [1,1,1,1]
            on_press: root.btn_push_press()


<MyRoundedButton_push@Button>:
    background_normal: ''
    background_color: (0, 0, 0, 0)
    back_color: (0, 1, 1, 1)
    pressed_color: (1, 0, 1, 1)
    border_radius: [100]
    canvas.before:
        Color:
            rgb: self.back_color if self.state == 'normal' else self.pressed_color
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: self.border_radius
```

**Additional context**
