### ISSUE TITLE
Request: Layouts, by default, should take dimensions of its parent

### ISSUE THREAD

**Issue by supercheetah** [kivy/kivy#857]
One of the things that I found confusing when I first started using Kivy was the behavior of layouts, e.g. GridLayout, FloatLayout, BoxLayout, etc.  I had assumed that their purpose was to control the way things were laid out, but I had a mistaken idea of how that mechanism worked.  So, let's we've got MyWidget which just inherits from Widget:

```
class MyWidget(Widget):
    pass
```

And then I create the Kivy code as such:

```
<MyWidget>
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "An useless label"
        TextInput:
            multiline: True
            text: "Stuff to be typed"
        Button:
            text: "Click me"
```

This doesn't exactly behave the way I would have expected it.  Of course the fix is the following:

```
<MyWidget>
    BoxLayout:
        orientation: 'vertical'
        size: self.parent.size
        Label:
            text: "An useless label"
        TextInput:
            multiline: True
            text: "Stuff to be typed"
        Button:
            text: "Click me"
```

What results from that is what I would have expected originally.  Basically, I think that layouts, if they're not the root widget, should take on the dimensions of its parent widget by default.  I think this is what most people would expect when using layouts.
