### ISSUE TITLE
  ActionOverflow crashes when there is an ActionSeparator

### ISSUE THREAD

**Issue by yves-surrel** [kivy/kivy#8738]
In example `widgets\actionbar.py`, if an`ActionSeparator` is added, shrinking the window to have ActionOverflow firing makes the window become black and then Kivy crashes.
```
from kivy.base import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string('''
ActionBar:
    pos_hint: {'top':1}
    ActionView:
        use_separator: True
        ActionPrevious:
            title: 'Action Bar'
            with_previous: False
        ActionOverflow:
        ActionButton:
            icon: 'atlas://data/images/defaulttheme/audio-volume-high'
        ActionButton:
            important: True
            text: 'Important'
        ActionButton:
            text: 'Btn2'
        ActionButton:
            text: 'Btn3'
        ActionButton:
            text: 'Btn4'
        ActionSeparator:   # <------------------ Added
        ActionGroup:
            text: 'Group1'
            ActionButton:
                text: 'Btn5'
            ActionButton:
                text: 'Btn6'
            ActionButton:
                text: 'Btn7'
'''))
```
MacOS, Python v3.9.13, Kivy v2.3.0
