### ISSUE TITLE
max_lines property reducing text from front 

### ISSUE THREAD

**Issue by Fector101** [kivy/kivy#8932]
** Kivy version 2.3.0 **
* Python: 3.12.3
* OS: Linux mint
* Kivy installation method: through pip

**Instead of removing additional lines from the end of the text it starts removing from beginning of text**

**Expected behavior**
After line 2 no more lines should be added 

**To Reproduce**
```

kv = """
Label:
    text: "Really long text with some lengthy description on subject"
    font_size: '11sp'
    size_hint: [None, None]
    size: (root.width, 40)
    text_size: (root.width, None)
    max_lines: 2
"""
```

Sample of bug:
![IMG_20241129_224458.jpg](https://github.com/user-attachments/assets/1c507044-2eb1-4824-8050-af83e4d78e6b)
