### ISSUE TITLE
Label stops rendering text when the number of lines gets too big

### ISSUE THREAD

**Issue by martin-91x** [kivy/kivy#8950]
**Software Versions**
* Python: 3.12.7
* OS: Windows
* Kivy: 2.3
* Kivy installation method: pip / poetry

**Describe the bug**
The label widget (inside a popup) stops rendering text when the number of lines gets too big.
This happens to me when I try to use a popup to show all the licenses used in my project.

**To Reproduce**
main.py
```python
from kivy.app import App
from kivy.uix.widget import Widget
from kivy.uix.popup import Popup

class PopupLicense(Popup):
    pass

class Frame(Widget):

    def show_popup(self):
        popup = PopupLicense()

        with open('LICENSES', encoding='utf-8') as f:
            license_text = f.read()

        popup.ids.lb_license_text.text = license_text
        popup.open()


class TestApp(App):
    def build(self):
        return Frame()


if __name__ == '__main__':
    TestApp().run()
```
test.kv
```
#:kivy 2.3.0

<Frame>:
    Button:
        text: 'Test Popup'
        on_release: root.show_popup()

<PopupLicense>:
    size_hint: (None, None)
    size: (640, 480)
    ScrollView:
        Label:
            id: lb_license_text
            halign: 'center'
            size_hint_y: None
            text_size: (root.width * 0.95, None)
            size: self.texture_size
            max_lines: 2000
```

Additionally, have a file called "LICENSES" with many lines ready to reproduce.

**Additional context**

This is mix max_lines set to 1500:
![Screenshot 2024-12-11 232924](https://github.com/user-attachments/assets/ff5039ff-1350-4fdc-b4e2-ea150212b150)
This is mix max_lines set to 2000 (or any large number or not set at all):
![Screenshot 2024-12-11 232859](https://github.com/user-attachments/assets/54a42523-669f-476f-b4a8-9b50f9852eb2)
